### ISSUE TITLE
Problem with include_directories on Macs

### ISSUE THREAD

**Issue by aleixpinardell** [Tudat/tudat#101]
This problem has been annoying me for a long time and I have finally found a candidate fix, but I don't know if it's safe to implement the fix.

My Qt Creator parser does not recognise the include files for tudat, eigen, boost, etc. I get this message:
<img width="502" alt="screen shot 2016-11-30 at 14 03 29" src="https://cloud.githubusercontent.com/assets/10518548/20753270/daf247f0-b705-11e6-8a9b-133f3288b595.png">

The consequence is that the code is not interactive: all text is displayed black, I do not get autocompletion or suggestions while writing, I cannot jump to the definition of functions, variables... However, the application compiles and runs fine.

I think the source of the error is in a piece of code that is repeated several times in some of the CMakeLists of the tudatBundle:
```
if(NOT APPLE)
  include_directories(SYSTEM AFTER "${pLaCeHoLdEr_DiR}")
else()
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem \"${pLaCeHoLdEr_DiR}\"")
endif()
```

Apparently the `include_directories` line is not run on Macs, so the Qt parser cannot find Tudat, Eigen, boost, etc. I've noticed that placing the `include_directories` outside of the `if` and running CMake solves the problem, but I don't know if it's safe to do this. I don't know what the line `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem ...` is supposed to do. And changing all the CMakeLists may cause conflicts in the future if I have to update them from the server.

**Comment by DominicDirkx** [comment]
Hi Jacco,

Could you test this solution on your test-Mac? If it works, we can update all the rest of the code accordingly,

Cheers,

Dominic

**Comment by magnific0** [comment]
Hi @aleixpinardell,
As per @DominicDirkx request I have investigated the issue. Using ```-isystem``` compiler flags instead of CMake's ```include_directories``` on Mac's seems outdated on modern systems. I did not find precisely, when this became obsolete and whether this is still necessary for some of our users. Therefore I have not removed the check completely.

Instead, I have included a CMake variable ```APPLE_INCLUDE_FORCE``` (in tudatBundle/CMakeLists.txt) that is on by default. For this to work you need to pull in new versions of tudatBundle, tudat, and tudatExampleApplications from the official upstream.

I have tested this on our test Mac and it seems to work fine. I'm closing the issue. Feel free to contact me for more details or if you find the issue should be reopened.

Also I'm very interested if users find it necessary to set ```APPLE_INCLUDE_FORCE``` to ```OFF``` on their system. Otherwise, this feature should removed in the future.

Regards,
Jacco
