### ISSUE TITLE
Moving Vector6d out of basic_mathematics, and Tudat Basic types in general

### ISSUE THREAD

**Issue by DominicDirkx** [Tudat/tudat#116]
As noted in issue #92, it would be a good idea to move the Vector6d typedef out of the basic_mathematics namespace, similarly to what has been done with the new Time type.

**Comment by magnific0** [comment]
We're discussing Vector6d, but I think we should consider things a bit broader. Nonetheless, Vector6d is a great example of where an intended simplification, does not achieve its goal. 

1. It lives in a double (pretty long second) namespace ```tudat::basic_mathematics::``, this means I have to type ```basic_mathematics::Vector6d```, unless I use ```using```, but in practice this is not done (516 usages of ```basic_mathematics::Vector6d``` versus 64 Vector6d + 11 using statements). 
2. and away from other related types Eigen::Vector3d. This means if I want to move from Vector6d to VectorXd, I also have to change the namespace instead of just replacing an X with a 6.
3. on top we always need to include the header (Tudat/Mathematics/BasicMathematics/linearAlgebraTypes.h) if we want to make use of this (and 5 other types). 

Overall it's pretty awkward.

There are two options as far as I can tell (save for leave as is):

**Option 1** typedef as Eigen::Vector6d.
As already mentioned by @DominicDirkx. The solution makes a lot of sense. It fits in great with Eigen::Vector3d etc. It is perhaps bad practice to use a namespace you don't have control over. However, what is the chance of a collision?

**Option 2** typedef as tudat::Vector6d
Just as tudat::TimeType now. Perhaps these should be also be relocated outside the folder structure, to say Tudat/Basic/types.h. Benefits are that we could also retypedef Vector3d and other commonly used Eigen types. Basically collect all common (from other libs) and unique (to tudat) basic types in one place, for easy use. 

Also while writing this: why TimeType and not Time?

**Comment by DominicDirkx** [comment]
In my opinion, option 1 makes the most sense. Since we ship Eigen with the bundle, we can always freeze the Eigen version that is used in case they define their own Vector6d. It also makes the code more 'symmetrical'. Putting all Eigen typedefs into the Tudat namespace seems a bit too laborious to me, just to be able to add this one Vector6d typedef.

**Comment by magnific0** [comment]
To be honest, if Eigen decides (they won't) to define Vector6d we would just drop ours. My reservations towards Option 1 are a bit more fundamental.

Also it is quite unexpected behavior if you need to include some Tudat library to unlock an Eigen feature. Especially for users who will write their own applications.

I agree that option two is more work and also not ideal, but it is not about defining all eigen types in tudat, just for the sake of wanting a Vector6d. It is about offering a lot of common types (own, Eigen, potentially libraries) under a common namespace. But yeah, the decisison of what gets adopted as an Tudat type and what not is not straightforward.

Perhaps just moving Vector6d out of basic_mathematics is the most practical. I would still argue for a single Basics/types.h header instead of ```Mathematics/BasicMathemacis/lineaAlgebraTypes.h```, because the scope doesn't have to be limited so strictly. The overhead of including some definitions you don't use outweighs completely the need of including multiple header files.
