### ISSUE TITLE
Implement C++11

### ISSUE THREAD

**Issue by kartikkumar** [Tudat/tudat#15]
Might be a good time to consider implementing C+11. All major compilers now support C++11 and there are a number of Boost libraries that are now shipped as standard (e.g., smart pointers, auto, initializer lists, lambda). A comprehensive list of features can be found on Stroustrup's website: http://www.stroustrup.com/C++11FAQ.html

The biggest advantage is that this would reduce the dependency on Boost, which is a pain to manage as a dependency.

**Comment by magnific0** [comment]
Tudat already builds with C++11 and uses vely sporidacally some of it's features. Boost independence sounds great but will require porting and other solutions (e.g. unit testing). For now we have decided to make our dealings with boost smoother.

**Comment by magnific0** [comment]
*very *its. Sorry for the horrible spelling.

**Comment by kartikkumar** [comment]
For unit-testing, see https://github.com/Tudat/tudat/issues/16

I've had a cursory look at the Boost features that are otherwise used, and generally it's just smart pointers and lambdas. Filesystem and random get used in places, but they can be refactored on the basis that a lot of the blocks of code that use those don't really belong in Tudat anyway.

**Comment by DominicDirkx** [comment]
Concerning both this and the points raised in https://github.com/Tudat/tudat/issues/16 and https://github.com/Tudat/tudat/issues/17, I think we can put this in the category of 'would be nice'. Since our time, and especially the amount of people actively working on Tudat, is limited, I don't think these points can reasonably be given any priority in the near future.

Instead, I plan to spend my time on the project on giving a greater focus on to adding functionality that makes it easier for students and other people to use the code. The original idea to let people write their own propagator/body/etc. classes to tie everything together was nice, but it has turned out that it is simply not feasible to expect students to learn how to do this during their theses. This has lead to Tudat not being used as well as it could, or simply not at all.

The focus of the development in the coming time, at least from my part, will be adding code from  my own software to Tudat, which makes setting up simulations much easier. This means reintroducing something similar to a body and propagator class. I stress that these new classes will not be _necessary_ to use the code, but allows students to at least get started quickly and easily.

With the Space Project starting again, we will see how well the new setup of boost in the project goes. With any luck, the new setup using the add_boost.cmake and compiler.cmake that Jacco created will capture many of the issues that have plagued us in the past. If this turns out to not be the case, we can always revisit making the code boost-independent, but for now I don't see any reason to give this priority.

**Comment by kartikkumar** [comment]
Sounds good. I'll leave it to you to set the development roadmap since I'm working on a new set of libraries.

**Comment by DominicDirkx** [comment]
With a number of the recent additions to the code, the boost dependency has grown a bit beyond what is available in C++11. It seems unlikely that we will be moving away from boost in the near future, so I'm closing this issue.
