### ISSUE TITLE
Output astronomical time in Doppler Observation Model

### ISSUE THREAD

**Issue by oscar93gonmar** [Tudat/tudat#173]
Hi,
I have a question regarding the output time of Tudat in the Doppler Observation Model. What I give as an input for the simulation start epoch is my UTC time in seconds since J2000, but I'd like to know whether the output time of the observation model is UTC or TDB, or whether I need to input the simulation start epoch in TDB rather than UTC.

If the output time is TDB, how can I use the function "convertEphemerisTimeToJulianDate" to change the output data map of the observation model to UTC? 

thank you in advance!
Oscar

**Comment by DominicDirkx** [comment]
Hi Oscar,

In principle, all times used as input to the dynamics and observation models are in TDB, as all ephemerides, gravitational parameters, etc. that we use are TDB-compatible (see this article: http://www.aanda.org/articles/aa/pdf/2008/06/aa7786-07.pdf for details).

The best way to convert UTC<->TDB is by using the functions in External/SofaInterface/sofaTimeConversions.h . 

These conversions go 'via' the TT time scale, so UTC<->TT<->TDB (which internally is implemented as UTC<->TAI<->TT<->TDB). Use convertTTtoUTC and convertUTCtoTT for the UTC<->TT step. There a number of options for the TT<->TDB conversion (several functions getTDBminusTT). For your purposes, using the last one should be fine:

double getTDBminusTT( const double ttOrTdbSinceJ2000, const Eigen::Vector3d& stationCartesianPosition );

Since the data you are looking at is quite inaccurate, you may even assume TT=TDB, the difference between the two is at the 2 ms level at most (see http://aa.usno.navy.mil/publications/docs/Circular_179.pdf, Eq. 2.6)

**Comment by oscar93gonmar** [comment]
Ok, thank you very much

**Comment by DominicDirkx** [comment]
No worries. Let me know if you get stuck or confused with any of the documents/conversions. As I mentioned last week, these various time scales can be a bit overwhelming when first confronted with them.

**Comment by oscar93gonmar** [comment]
I am trying to use convertUTCtoTT but I get this error message: sofa/src/sofa.h not found. Which appears in sofaTimeConversions.h as
extern "C"
{
#include "sofa/src/sofa.h"
#include "sofa/src/sofam.h"
}
I am wondering whether I need to download these files since I cannot find them in the TudatBundle folder.
Thanks, Oscar

**Comment by DominicDirkx** [comment]
Hi Oscar,

I was under the impression that you were already working with the latest version of the code: you need to checkout the FullOrbitDetermination branch of tudatBundle, which should retrieve sofa as well.

I am curious, without Sofa how did you perform the UTC<->TDB conversion for the results you showed yesterday?

Have a nice weekend,

Dominic

**Comment by oscar93gonmar** [comment]
Hi Dominic,
I decided to have everything in TDB rather than in UTC, so I did not have to change the results of Tudat but the ones of the Matlab code. I found a Matlab package in Mathworks that had also implemented a function for the UTC <-> TDB conversion. However, since the results had a time shift, we discussed yesterday to use Sofa to check if we obtain the same results.

**Comment by DominicDirkx** [comment]
Ok, good idea. Let me know how it works out.

**Comment by oscar93gonmar** [comment]
Hi Dominic,
I performed the time conversions and all seemed to work well. However, I am still getting this difference of ~18s at the time of closest approach when comparing the range-rates with SGP4. I checked that the range-rate given by Tudat in the doppler observation model is the derivative of the range, and these values coincide. As an additional check, I obtained the range (and then range-rate) from the results of the propagation in Tudat, that is, computing the vector between the station at the satellite in ECEF reference frame and then the range-rate at each instant. Proceeding in this manner, the results I get are really close to those of SGP4 but differ from the output range and range-rate of the observation model in Tudat. Bart and I were wondering if this might be due to some differences in the reference frames (maybe I need to specify the reference frame in the observation model?) 
Thanks,
Oscar

**Comment by DominicDirkx** [comment]
Hi Oscar,

I'm a bit confused about what you are comparing. If you'd like me to have a look at it before Tuesday, write up a short document, with clear equations showing what is being computed where, what the results and why this is puzzling. Otherwise, drop by Tuesday after 17:00,

Cheers,

Dominic

**Comment by oscar93gonmar** [comment]
Hi Dominic,
Ok, I think it will be easier to explain it in person, so I will prepare some results and we can discuss about them on Tuesday.
See you, 
Oscar
