### ISSUE TITLE
Write to a file the output of the Orbit Determination

### ISSUE THREAD

**Issue by oscar93gonmar** [Tudat/tudat#178]
Hi,
I have run the orbit determination module to estimate the initial state of a satellite based on simulated range-rate measurements with the one way doppler observation model. I would like to know how can I write the estimated initial state to a file, and if possible, to show them on the screen.
Thanks in advance,
Oscar

**Comment by DominicDirkx** [comment]
Hi Oscar,

In InputOutput/basicInputOutput.h, there is a function writeMatrixToFile. You can use this to write any Eigen MatrixXd (of which an Eigen VectorXd, Vector3d, etc. is a specific case) to a file. The values in the vector of estimated parameters is stored in the parameterEstimate_ member of an object of the PodOutput class. You can alwasy print this to the terminal with a simple cout command. Let me know if this helps you out,

Dominic

**Comment by DominicDirkx** [comment]
By the way, I started playing around in the code to add the estimation of observation biases. It turns out that it wasn't as much of a hassle as I had thought. In fact, it seems to be working:

https://github.com/DominicDirkx/tudat/tree/ObservationBiasEstimation

A preliminary test that includes bias estimation is included orbitDeterminationCases.h. It still needs some polishing up (and of course documentation), but the basics are there,

Dominic

**Comment by oscar93gonmar** [comment]
Ok thank you, I will have a look at it!
