### ISSUE TITLE
Does getStateDerivativeFunction refers to enum?

### ISSUE THREAD

**Issue by mvandenbroeck** [Tudat/tudat#182]
Hi,

If I would put `std::cout << this->getStateDerivativeFunction( ) << std::endl;` at [this](https://github.com/Tudat/tudat/blob/master/Tudat/Mathematics/NumericalIntegrators/rungeKuttaVariableStepSizeIntegrator.h#L456) line, it gives me the following output: `1`.

My question is now: Does this `1` refer to an enum. If yes, is it [this](https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/Propagators/singleStateTypeDerivative.h#L28) enum?

A follow-up question would be: When `this->stateDerivativeFunction( )` is called at [this](https://github.com/Tudat/tudat/blob/master/Tudat/Mathematics/NumericalIntegrators/rungeKuttaVariableStepSizeIntegrator.h#L459) line, where does it actually refer to? I.e. where is the code that actually calculates the current state derivative?

I tried ctrl+clicking, but I get really confused with all the links. I know that in my case (using a central gravity field + thrust accelerations), the code should eventually link to [here](https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/Gravitation/centralGravityModel.cpp#L41-L43) and [here,](https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/Propagators/nBodyStateDerivative.h#L366-L368) but what path does it take in between? I need the path to know where to place output statements. I need the output statements to find the cause of the difference in the trajectories resulting from two propagators that are expected to give the same output.

Thanks for your help,

Michael

**Comment by magnific0** [comment]
Hi Michael, in C++ ```this``` is [a pointer that points to itself](https://www.tutorialspoint.com/cplusplus/cpp_this_pointer.htm). It returns a boost::function of a specific typedef (e.g. StateDerivativeFunction) as defined [here](https://github.com/Tudat/tudat/blob/master/Tudat/Mathematics/NumericalIntegrators/numericalIntegrator.h#L47-L48). 
Boost functions are pretty great and allow for function and member function of specific objects to be wrapped into an object that can be passed around. They are a bit difficult to understand if you haven't explicitly used them yet. They are very similar to Matlab's [anonymous functions](https://nl.mathworks.com/help/matlab/matlab_prog/anonymous-functions.html), which you might have ran into. Otherwise try to [read up a bit](http://www.boost.org/doc/libs/1_64_0/doc/html/function/tutorial.html) on them.
Directing this boost::function to the ```std::cout``` does not make sense. Instead you should query the function for something. 
So try something like:

    StateDerivativeFunction s = this->getStateDerivativeFunction( );
    std::cout << s(0.0, state) << std::endl;

**Comment by magnific0** [comment]
One last note, you are working inside the class itself, however, if you have access to your integrator or simulator object in your application, it makes more sense to do it there, so:

    StateDerivativeFunction s1 = rkf87->getStateDerivativeFunction( );
    StateDerivativeFunction s2 = dynamicsSimulator->getStateDerivativeFunction( );
    std::cout << s1(0.0, state) << s2(0.0, state) <<std::endl;

Note that the DynamicsSimulator also has the same function (by design) [defined here](https://github.com/Tudat/tudat/blob/c27baa95f605e1c0e8eac36cfdf3d8a4559e6d5d/Tudat/SimulationSetup/PropagationSetup/dynamicsSimulator.h#L256).

**Comment by mvandenbroeck** [comment]
Thanks for the reply @magnific0 !

I'm working on following your tips and links.

**Comment by DominicDirkx** [comment]
Hi Michael,

A small addition to magnific0's comments: the state derivative function in the integrator is linked to the computeStateDerivative function of an object of type DynamicsStateDerivativeModel, defined in [this file:](https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/Propagators/dynamicsStateDerivativeModel.h
)
- updateMembers function of ThrustAcceleration and CentralGravitationalAccelerationModel are called by

**Comment by mvandenbroeck** [comment]
Hi Dominic,

Thanks a lot for your extensive reply!
I'm using the Cowell method indeed.

I'm working on it!

Cheers,

Michael
