### ISSUE TITLE
Moon spherical harmonic gravity field

### ISSUE THREAD

**Issue by BeatrizMOliveira** [Tudat/tudat#184]
I've seen in the wiki that the default gravity model used for the Moon is called GGLP, but I cannot find any information about it. Is it possible to give the complete name/source?

Thank you.

**Comment by DominicDirkx** [comment]
Certainly, GGLP is the lunar is the lunar gravity field generated from Lunar Propspector data, its documentation can be obtained here:

http://pds-geosciences.wustl.edu/lunar/lp-l-rss-5-glgm3_gravity-v1/lp_1201/data/shadr/

with many more gravity fields available here:

http://pds-geosciences.wustl.edu/dataserv/gravity_models.htm

It's not a particularly accurate gravity field, but for any preliminary analysis it gets the job done. If you want very accurate models, download the GRAIL gravity fields, their accuracy is really quite amazing. We're not shipping them with Tudat because the data files are pretty big, and it's not necessary for most users.

Let me know if you need any more info,

Dominic

**Comment by BeatrizMOliveira** [comment]
When you say it's not very accurate, do you mean the constants themselves could be better or that there is a small number of degrees and orders available?

Thank you very much for the answer!

**Comment by DominicDirkx** [comment]
Hi Beatriz,

Actually, both! The GRAIL gravity fields are orders of magnitude more accurate than than the LP fields, and coefficients go up to degree and order 1500. The question is if this is relevant for your application. In the PDS (see link in previous post), there are typically reference to papers describing the gravity fields, where the details on e.g. degree variance are provided. For the LP field, note that the rear side is still relatively poorly determined,

Best,

Dominic

**Comment by DominicDirkx** [comment]
Actually, this paper:

http://science.sciencemag.org/content/339/6120/668.full

has a nice plot of the degree variance of gravity fields from LP, Selene and GRAIL. Now that I think of it, we should probably update the Tudat field for the Moon, and provide a GRAIL field truncated at a 'low' order.

**Comment by BeatrizMOliveira** [comment]
Thank you very much for your help!

I'm glad Tudat is continuously being improved.

**Comment by DominicDirkx** [comment]
Definitely, and if you have any suggestion for missing features, or things that you would like to see improved, don't hesitate to let us know!
