### ISSUE TITLE
Request for new functionality: rotational dynamics & wind model

### ISSUE THREAD

**Issue by gviavattene** [Tudat/tudat#205]
Hi everyone, 
I am using Tudat for my thesis work and, as discussed with Dominic, I need the rotational dynamics implemented. The sources of torques are gravity, aerodynamics and thrust. Moreover, to conduct my analysis I need a complete wind model, which includes steady-state wind, turbulence and wind gusts. I can provide you their models. Do not hesitate to contact me for any additional information. 

Thank you!

Best regards,
Giulia Viavattene

**Comment by DominicDirkx** [comment]
A first implementation of rotational dynamics has been implemented:

https://github.com/DominicDirkx/tudat/tree/RotationalDynamics

It contains interfaces for using torques, but none are now implemented. The unit tests are not yet completely robust, but they are a very good start. Due to some serious issues with the Tudat server the website is down, and documentation for this functionality is not yet available. Hopefully this will be resolved soon, but I should be adding comments to the code very soon. 

When you are getting close to needing these models, let me know and I can explain the basic functionality and architecture. Also, start thinking about the formulation of the torques that you'll need and, very importantly, how to test their correct implementation,

Dominic

**Comment by DominicDirkx** [comment]
An update on this: the rotational dynamics unit tests have been expanded and are now much more comprehensive. Only the overall propagation of rotational dynamics (both by itself and concurrently with translational dynamics) are tested, the correct computations of the torques has not been tested yet. The code has been pushed to the Tudat development branch:

https://github.com/Tudat/tudat/tree/development

A first iteration of a wind model architecture has also been implemented:

https://github.com/DominicDirkx/tudat/tree/WindModels

Some of the code was based on that linked to here: #102 . However, for simplicity the wind vector is now computed in the central-body-fixed frame (e.g. ECEF for Earth central body). A next iteration should have the option of selecting the frame in which the wind vector is defined. Let's discuss your requirements when it becomes relevant. I'll push the current wind model code to the Tudat development branch when comments have been added.

I'm closing this issue, as the basic functionality has been implemented. For next steps, which will most likely be more specific models, as opposed to the overall architecture, I think it'll be easiest to discuss those in separate, dedicated issues.

Dominic
