### ISSUE TITLE
Error while building the TudatBundle project

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#207]
Hi Dominic,

I am working on Linux and have installed the Tudat. However I am having issues when building the project.

After downloading the tudatBundle from the github account following the steps described there, I have tried to update the tudat to the ultimate version of the FullDevelopmentBranch  branch using the Linux terminal commands (opening the terminal from the tudat folder) that you had described me some time ago:

git fetch https://github.com/Tudat/tudat

git merge https://github.com/Tudat/tudat/FullDevelopmentBranch

but I always get an error saying “not something we can merge”.

Therefore I have manually downloaded all the FullDevelopmentBranch tudat files and merged them manually with the previous tudat folder.

In the end, I have issues when building the project and the compile output is attached.

[Compile_output.txt](https://github.com/Tudat/tudat/files/1121561/Compile_output.txt)

Could you please help me?

Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

A few questions

1) Which branch did you manually merge the FullDevelopmentBranch into? You can do 'git branch' to get this information. Please, make sure that you revert to a situation where you have a master branch, and a FullDevelopmentBranch both corresponding to those on the repository. Otherwise pulling code updates will be impossible. Manually downloading the code and merging it is a recipe for disaster. Please, when faced with something fundamental like this that impacts your entire Tudat installation, just open an issue to ask for assistance. The fix is very easy, and it'll probably take more time from both of us now to get it into working order. Since I'm now not sure what you've done exactly, it's more difficult for me to help you correct it. Have a look at this page to understand how to get everything in proper working order: 

https://help.github.com/articles/fetching-a-remote/

if it's not clear, please let me know

2) Which compiler (and compiler version) are you using?

3) Which boost version are you using?

4) Did the master branch compile properly?

The problem looks like an incompatibility between boost and the compiler (see attached documentation page, section 2.1).
[troubleshooting.pdf](https://github.com/Tudat/tudat/files/1121613/troubleshooting.pdf)

 Let me know,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

In order to make things more easy to understand I downloaded again the tudatBundle and did everything from the start again, having read the git guide that you’ve sent me.

 The tudatBundle (master branch, checked with the command ‘git branch’) configures and builds correctly.  In order to move to the FullOrbitDetermination branch I opened the terminal on the tudatBundle folder and typed:

git fetch origin

git merge origin/FullOrbitDetermination

The merge is successful but when I configure the project again an error occurs: it is related to the sofa subdirectory which does not exist. Even if I have merged with the FullOrbitDetermination branch, I realize that the folder sofa is totally empty and its content has not been downloaded to my computer.

What can I do from the terminal?

Regarding the other questions, the boost version is 1.60 and when I check the compiler through the terminal by typing ‘gcc -v’ I get ‘gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2)’

Thanks for the support

Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

To retrieve the sofa folder, type:

 git submodule update --init --recursive

This will retrieve the code from all submodules (of which sofa is one).

First, have you tried to compile the master branch? To speed up the process, are you using multi-core compilation? 

The GCC version you are using is very new, so try using a newer version of Boost. For 1.63, try:

set(BoostVersion 1.63.0)
set(BoostSHA1 9f1dd4fa364a3e3156a77dc17aa562ef06404ff6)

instead of the associated code for 1.60 in the top-level  CMakeLists,

Dominic

**Comment by ggranato92** [comment]
Hi Dominic,

when I do 'git submodule update --init --recursive' I get fatal error: No url found for submodule 'pykep' in .gitmodules

I had compiled the master branch and everything goes well, only a few warnings but it is successful. How can I use multi-core compilation? Shall I run a particular command from the terminal for that?

**Comment by DominicDirkx** [comment]
That's funny.... Could you attach your .gitmodules file here. It's in the same directory as your top-level CMakeLists; you may have to change the extension for Github to allow you to attach it.

For the master branch, have you run all the unit tests?

You can set multicore compilation as follows:

![image](https://user-images.githubusercontent.com/5039068/27836305-212f8902-60df-11e7-88ff-6b79fcd0fada.png)

The -j12 argument indicates that I use 12 threads. Even with 16 GB, 12 threads will probably eat up all your RAM. Start with -j4 and see how your RAM usage goes.

**Comment by ggranato92** [comment]
I cannot find that file in that directory...apparently there is no gitmodule. Also making a search in the computer doesn't help..I think this is the problem then. What can I do?

I haven't run the tests yet since I wanted to run everything with the full development branch

Thank you for the compilation setting explanation

**Comment by DominicDirkx** [comment]
I'm pretty sure the file has to be there, if it isn't the bundle wouldn't work at all. My file manager looks like this

![image](https://user-images.githubusercontent.com/5039068/27839662-50137af8-60f3-11e7-8f19-41cdf9414f03.png)

However, the .gitmodules may be a hidden file. It is in my terminal with a normal ls command. If I do ls -al, however, it shows up. Then, typing gedit .gitmodules opens the file. See below

![image](https://user-images.githubusercontent.com/5039068/27839705-b100203c-60f3-11e7-9b7d-0489cbdcaa15.png)

Hope this helps.

For the master branch, could you also run the unit tests? Any failures here is one less thing to worry about when you run the full latest version of the code. Additionally, if you only test the latest FullDevelopmentBranch, and you get any failures, it's impossible to know if this is due to new code, or due to stable code in the master branch that you are using.

**Comment by ggranato92** [comment]
Hi Dominic,

I have run all the unit tests from the master branch and everything works perfectly, without making any modifications to the files cloned from the tudatBundle repository.

I have found my .gitmodules file, it was a hidden file in my computer. It is exactly equal to yours, I am attaching it here below.
[gitmodules_file.txt](https://github.com/Tudat/tudat/files/1124169/gitmodules_file.txt)


At this point, if I open the terminal in the tudatBundle folder and type ‘git status’ it says that I am on branch master and that my branch is up-to-date with ‘origin/master’.
If I do git branch I get ‘*master’ and if I type ‘git log - - oneline - - decorate’ I get the following:

![screenshot_commang_git_log](https://user-images.githubusercontent.com/28297936/27858869-26d137b4-6177-11e7-95fa-0c9c518d6fe6.png)

From this situation, how can I proceed to move to the FullOrbitDevelopment branch? I actually do not see that branch appearing in the output of my 'git log' command. Also, how shall I update the tudat to the FullDevelopmentBranch as well?


Thank you very much

Giovanni

**Comment by DominicDirkx** [comment]
Good to hear that all unit tests passed!

If you do 'git branch' you get a list of all branches. This should include the one you want, you can do 'git checkout <Branch Name>' to check out the branch you want. If you are missing some branches that are on Github do 'git fetch upstream' and this will get you all branches that are on the upstream remote.

**Comment by ggranato92** [comment]
When I type 'git branch' I get only the master branch on which I am now but no more branches appear. So I typed 'git fetch upstream' but the output is:
fatal: 'upstream' does not appear to be a git repository
fatal: could not read from remote repository

Please make sure you have the correct access rights and the repository exists

**Comment by DominicDirkx** [comment]
Ok, type 'git remote -v', this will show you which remotes you have. If your https://github.com/tudat/tudatBundle.git remote is called 'origin' (or something else) replace the upstream with this name instead

**Comment by ggranato92** [comment]
I have followed your steps but I still get only the master branch when I type 'git branch'. In order to see the other branches I have typed 'git branch -a' and I am attaching the output.
![git_branch](https://user-images.githubusercontent.com/28297936/27862133-1aa473ea-6184-11e7-9b3c-7c16fdda5483.png)

What is the meaning of this output? How can I get the other branches on my local repository? In particular, what is the meaning of the second red line? (remotes/origin/HEAD -> origin/master)

**Comment by DominicDirkx** [comment]
That's odd, I haven't seen this before. Anyway, this stackoverflow page:

https://stackoverflow.com/questions/10312521/how-to-fetch-all-git-branches

seems to discuss this issue. If you do git fetch -all, you should have access to all the branches.

**Comment by ggranato92** [comment]
Hi Dominic,

I have been reading that page and searching for several other git guides to try to solve the issue but I haven’t had any luck. I really do not understand the reason why it doesn’t work. 

I have created a new local branch that tracks the remote FullOrbitDetermination branch by typing ‘git checkout –track origin/FullOrbitDetermination’. I have so shifted to the new local branch created (called FullOrbitDetermination as well). The situation is pictured in this image
![git_remote_show_origin](https://user-images.githubusercontent.com/28297936/27904284-825efc86-623c-11e7-8648-4cd47b7c55a2.png)


When from my local FullOrbitDetermination branch I type ‘git fetch origin’and ‘git merge origin/FullOrbitDetermination’ it says that it’s already up to date but when I run cmake the configuration of the project has errors and is incomplete.  The issue which is displayed is ‘/home/giovanni/tudatBundle/CMakeLists.txt:93: error: add_subdirectory given source "/home/giovanni/tudatBundle//sofa/src" which is not an existing directory’. Therefore I type ‘git submodule update –init –recursive’ but, again, I get always the same error: ‘fatal: No url found for submodule 'pykep' in .gitmodules’.

I have no idea what to do to fix this. I am attaching my Cmake output log and Cmake error log files in case they can be helpful
[Cmake_output_log.txt](https://github.com/Tudat/tudat/files/1127354/Cmake_output_log.txt)

[CMake_error_log.txt](https://github.com/Tudat/tudat/files/1127353/CMake_error_log.txt)

Thanks for the support,
Giovanni

**Comment by ggranato92** [comment]
I forgot to specify in the beginning that, of course, I tried the 'git fetch -all' command first, but it does not make any difference

**Comment by DominicDirkx** [comment]
Add this:

[submodule "pykep"]
	path = pykep
	url = https://github.com/esa/pykep

to your gitmodules file, try 'git submodule update –init –recursive' again, and let me know what happens. If it doesn't work, you can drop by at 14:00 today and we can have a look. Let me know before 13:30 if you want to come by

**Comment by ggranato92** [comment]
I have just done it. It clones the sofa folder but still some error occurs and it does not work. This is the output:
![submodule_update](https://user-images.githubusercontent.com/28297936/27907763-3f5e1dd8-6249-11e7-9ef7-e26d9869a7c4.png)

Seems we have made a step forward but not yet solved. Shall I come at 14 then?

**Comment by DominicDirkx** [comment]
Ok, drop by at 14:00 then.

**Comment by ggranato92** [comment]
Hi Dominic,

I have some positive news: after configuring properly the tudat project getting on the ultimate development branches of both tudatBundle and tudat, all the unit tests passed. 0 failures out of 167 tests and no issues!

Thank you for the support,
Giovanni

**Comment by DominicDirkx** [comment]
Good!
