### ISSUE TITLE
Issue when using function convertUTCtoTT

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#224]
Hi Dominic,

I am having problems with the function convertUTCtoTT. When I run my code there is an issue related to that function saying:

CMakeFiles/application_FileReading.dir/File_reading.cpp.o:-1: In function `double tudat::sofa_interface::convertUTCtoTT<double>(double)':

/home/giovanni/tudatBundle/tudatApplications/RadioAstronApplications/RadioAstronPropagation/File_reading.cpp:-1: error: undefined reference to `tudat::sofa_interface::getDeltaAtFromUtc(double)'

:-1: error: collect2: error: ld returned 1 exit status

Is there anything that I am missing in order to properly use that function? 

Thank you,
Giovanni

**Comment by DominicDirkx** [comment]
'undefined reference' generally means that you are now linking against the correct libraries. Could you attach the CMakeLists in which you create the executable here? (you may need to change the file extension)

**Comment by ggranato92** [comment]
Here is the CmakeLists file. [CMakeLists.txt](https://github.com/Tudat/tudat/files/1180112/CMakeLists.txt)
The application that I am now checking is called FileReading.

Thank you very much and sorry for the emoticons in the previous message: I just copied and pasted the errors as they appeared on screen and the emoticons came out in this window.

**Comment by DominicDirkx** [comment]
Yes, indeed the problem is that sofa is not included in your link libraries, Have a look at the Tudat CMakeLists, you will see two blocks that reference sofa. First, the 'if(NOT USE_SOFA)' statement (and everything inside the if statement). Second, the 

list(APPEND TUDAT_EXTERNAL_LIBRARIES tudat_sofa_interface sofa)

line.

The first locates sofa, the second tells the code to link to it when building. Add both parts to your code as well, (changing TUDAT_EXTERNAL_LIBRARIES to TUDAT_APPLICATION_EXTERNAL_LIBRARIES). You may need to copy the tudat 'findSofa.cmake' file to your application's directory with cmake modules, but it might be detected automatically. 

Let me know how it works out

**Comment by ggranato92** [comment]
I have followed your instructions and now everything works fine. Thank you a lot!

**Comment by DominicDirkx** [comment]
Good to hear!
