### ISSUE TITLE
Failure unit test: test_SphericalHarmonicPartials

### ISSUE THREAD

**Issue by magnific0** [Tudat/tudat#273]
$ gcc -v
    > gcc version 5.3.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project)
    $ ver
    > Microsoft Windows [Version 10.0.16299.19]

My boost version is 1.64. Both development-json and dev_dd+ap branches have this problem.

```
C:\tudatBundle\build>..\tudat\bin\unit_tests\test_SphericalHarmonicPartials.exe
Running 2 test cases...
Warning, creating parameter to estimate complex Love number at order 0, but imaginary part has no influence on dynamcis

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by DominicDirkx** [comment]
I have encountered this error before, and it is somehow due to an exception that is not being caught, see lines 611-666 of 

https://github.com/Tudat/tudat/blob/development-json/Tudat/Astrodynamics/OrbitDetermination/AccelerationPartials/UnitTests/unitTestSphericalHarmonicPartials.cpp

The tests may actually be a but misplaced, as they test the parameter objects, not the partials. I figured it would be easier to do a 'two-in-one' test here. The errors are thrown when creating the parameter objects:

https://github.com/Tudat/tudat/blob/development-json/Tudat/SimulationSetup/EstimationSetup/createEstimatableParameters.cpp

Lines 619-738

**Comment by DominicDirkx** [comment]
Issues due to exceptions not being caught has been corrected by an update to compiler.cmake.
