### ISSUE TITLE
Failure test - RotationalDynamicsPropagation

### ISSUE THREAD

**Issue by mmanzi95** [Tudat/tudat#293]
Mac computer, I got this:
![schermata 2017-11-15 alle 14 39 29](https://user-images.githubusercontent.com/33622899/32839344-681d3668-ca14-11e7-939d-c9b46c0c1ce7.png)

**Comment by DominicDirkx** [comment]
Thanks for reporting this. In the installation guide, we list a few files that we need to determine what this problem is. Could you post those as well?

The good news for you is that for the assignments, there is no numerical propagation of rotational dynamics, so it's unlikely that this will affect your assignments.

**Comment by mmanzi95** [comment]
I already run another programme, so I don't have the file you need anymore in /Testing/Temporary.
If you need it I can run it again.

**Comment by DominicDirkx** [comment]
Yes, please do. Thank you.

**Comment by mmanzi95** [comment]
This time it worked, sorry.


![schermata 2017-11-15 alle 16 10 02](https://user-images.githubusercontent.com/33622899/32843222-7fd447dc-ca1f-11e7-9533-b9273d27aaff.png)

**Comment by DominicDirkx** [comment]
That's very strange, but since the problem seems to be solved, I'm closing the issue. Thanks for rerunning everything.
