### ISSUE TITLE
Error when estimating relative observation bias in one and two way doppler observables

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#324]
Hi Dominic,

Concerning the OD simulations that I am running, I am trying to estimate a relative observation bias in the one and two way doppler observables but the software crashes giving the error: call to empty boost::function. The observation settings are fine (you looked at them during our last meeting) so I don't know what is the reason of this error. From the following screenshot you can see the last commit I'm using

![last_commit](https://user-images.githubusercontent.com/28297936/35511471-5ae48924-04fc-11e8-9fee-232df82e9110.PNG)

Thanks,
Giovanni

**Comment by DominicDirkx** [comment]
Thanks, I'll have a look when I can. For completeness, please also paste the full output you get, and the .cpp file with the main function.

**Comment by ggranato92** [comment]
I am attaching a txt file with the full output that I get. I will soon send you an email with the .cpp file and the file I upload. Thanks a lot

[Output.txt](https://github.com/Tudat/tudat/files/1674683/Output.txt)

**Comment by DominicDirkx** [comment]
Hi Giovanni,

I've found the source of the error, and I think it's something we've seen before. You have this line:

std::cout<<"Parameters B: "<<parametersToEstimate->template getFullParameterValues< double >( ).transpose( )<<std::endl;

Before the creation of the OrbitDeterminationManager, which means that the observation models nd parameters have not yet been linked, and the code fails.

**Comment by DominicDirkx** [comment]
Hi Giovanni,

I've been trying to find the issue in your code, and it seems that, in addition to teh above, there is a problem in your definition of the covariance matrix. Somewhere, something is being accessed out of bounds, leading to segmentation faults later in the code. These issue are notoriously hard to find, and I've lost quite some time trying to find it. 

I'd advice you to make the definition of the covariance more flexible: when you change parameter settings, make sure you only have to change a _single_ line of code. Otherwise, strange issues as this one may happen, where the parameter set and covariance are no longer consistent,

Dominic
