### ISSUE TITLE
Documentation for PropagationTimeTerminationSettings has incorrect constructor arguments

### ISSUE THREAD

**Issue by J-Westin** [Tudat/tudat#327]
The Tudat documentation website claims that PropagationTimeTerminationSettings takes a termination time and a boolean as constructor arguments: [Documentation](http://tudat.tudelft.nl/tutorials/tudatFeatures/propagationSetup/propagatorSettingsTermination.html)

This conflicts with the Doxygen declaration of the same constructor which only takes a double: [Doxygen](http://doxygen.tudat.tudelft.nl/de/d9e/classtudat_1_1propagators_1_1_propagation_time_termination_settings.html#a95ce20a4274834deb7fc8f5b0eddc3b8)

The latter signature appears to work, while the former does not.

Furthermore, on the former documentation page there appears to be a typo in the example code specifying the use of `PropagationTerminationSettings` rather than `PropagationTimeTerminationSettings`.

**Comment by DominicDirkx** [comment]
Hi Johan,

Thanks for spotting this. We merged some new documentation of upcoming features today, but were a but too enthusiastic. I rolled back the documentation, so that the input is now consistent with the code.

Concerning the typing error: you are indeed correct. @ifodde, could you update this in one of the next updates?
