### ISSUE TITLE
Issue in propagationTermination.cpp

### ISSUE THREAD

**Issue by ggranato92** [Tudat/tudat#344]
Hi Dominic,

I am having an issue when compiling the tudat after updating my local branch to the latest master branch. The issue occurs in the propagationTermination.cpp file and it says:

/home/giovanni/Downloads/tudatBundle/tudat/Tudat/SimulationSetup/PropagationSetup/propagationTermination.cpp:-1: error: undefined reference to `tudat::root_finders::doesRootFinderRequireDerivatives(boost::shared_ptr<tudat::root_finders::RootFinderSettings>)'

Due to this I don’t manage to run my applications..

Thanks for your support,
Giovanni

**Comment by DominicDirkx** [comment]
Hi Giovanni,

Thiis due to the fact that we made a few new Tudat libraries that you also have to link against. Update your application CMakeLists.txt as follows:

https://github.com/Tudat/tudatExampleApplications/blob/master/satellitePropagatorExamples/SatellitePropagatorExamples/CMakeLists.txt#L178-#L214

and all should be fine,

Best,

Dominic
