### ISSUE TITLE
Ephemeris not set automatically

### ISSUE THREAD

**Issue by JuliusWeinmiller** [Tudat/tudat#356]
Hello,

The ephemeris of a vehicle is not set automatically in the TranslationalStatePropagatorSettings.
The vehicle experiences aerodynamic, thrust, and gravity accelerations in the Earth's atmosphere with a MassRateModel from thrust.
The workaround is for this bug is manually adding both the ephemeris and massmodel, but setting the ephemeris should be done automatically by tudat. 

`bodyMap[ "Vehicle " ]->setEphemeris( boost::make_shared< ephemerides::TabulatedCartesianEphemeris< > >(
                                            boost::shared_ptr< interpolators::OneDimensionalInterpolator
                                            < double, Eigen::Vector6d > >( ), "Earth", "J2000" ) );`
`bodyMap[ "Vehicle " ]->setBodyMassFunction( boost::lambda::constant( Mass) );`

**Comment by DominicDirkx** [comment]
Functionality should be documented better. No changes in setup are foreseen: ephemeris is only reset if
- Flag to DynamicsSimulator is set so that the solution is processed in the environment
- The propagated body has a tabulated ephemeris

@ifodde Could you update this in a future wiki modification?
