### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by mfacchinelli** [Tudat/tudat#364]
Hello, 

I am trying to add the unified state model (USM7) to the set of Tudat propagators by following the wiki, but I get the following error:
```
Undefined symbols for architecture x86_64:
  "Eigen::Matrix<double, 7, 1, 0, 7, 1> tudat::orbital_element_conversions::convertCartesianToUnifiedStateModelWithQuaternionsElements<double>(Eigen::Matrix<double, 6, 1, 0, 6, 1> const&, double)", referenced from:
      tudat::propagators::NBodyUnifiedStateModelWithQuaternionsStateDerivative<double, double>::convertFromOutputSolution(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, double const&) in unitTestWindModel.cpp.o
  "Eigen::Matrix<double, 6, 1, 0, 6, 1> tudat::orbital_element_conversions::convertUnifiedStateModelWithQuaternionsToCartesianElements<double>(Eigen::Matrix<double, 7, 1, 0, 7, 1> const&, double)", referenced from:
      tudat::propagators::NBodyUnifiedStateModelWithQuaternionsStateDerivative<double, double>::convertToOutputSolution(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, double const&, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1>, -1, -1, false>) in unitTestWindModel.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
when I try to build the code. I based the new propagator class on the preexisting Gauss  propagators, so I don't understand where the error comes from. It may have to do with the fact that the USM7 has seven elements in the state vector, instead of six. 

You can find the changes I have made to the code on my GitHub, [here](https://github.com/mfacchinelli/tudat/tree/master). I also attached a [text file](https://github.com/Tudat/tudat/files/1881046/tudat_error.txt) with the complete compile output. 

Let me know if you need anything else.

Thank you and kind regards, 

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

I'll have a quick look, I think I know what the problem is, and I think I can make a 'quick fix'. Next week I'll have time to explain in a bit more detail. I'll push (hopefully) a fix in a couple of minutes.

You seem to be making very good progress! A few things to take inot account:
- Be critical about the Keplerian<->USM transformations that were already in Tudat. Someone reported some strange results from these functions recently. Perhaps run a test yourself if things come out funny.
- By converting Cartesian<->Keplerian<->USM, you may be subject to the singularities of Kepler elements (as you pass through potentially singular variables). To do it fully singularity-free, it should be implemented directly as Cartesian<->USM. Something to possibly think about once the code is up and running

Dominic

**Comment by DominicDirkx** [comment]
I've pushed some corrections here:

https://github.com/DominicDirkx/tudat/tree/michele-usm

It seems to be compiling better now. I'm recompiling/running all unit tests now, to see if it is indeed succesful.

**Comment by mfacchinelli** [comment]
Hi Dominic, 

Thank you very much! I'll implement the changes and I will keep in mind the suggestions. I transformed to Cartesian through Keplerian to be able to see if the implementation worked more quickly, but I will definitely make something more robust in the near future.

**Comment by DominicDirkx** [comment]
Hi Michele,

Great, sounds good. I've pushed one more small change, now all unit tests compile and pass. I guess you saw it already, but just in case, here:

http://tudat.tudelft.nl/developerGuide/addingFeatures/addFeatures.html#adding-a-new-state-derivative-model

is our new guide on implementing a new state derivative model. If you have any comments on it, don't hesitate to let us know,

**Comment by mfacchinelli** [comment]
Hi Dominic, 

I have seen it, yes. What you could add is a reminder to add the `#include` statements, for instance in the `createStateDerivativeModel.h` file, and that one can find the `TranslationalPropagatorType` enum in the `nBodyStateDerivative.h` file. Otherwise, it was all quite clear, especially if one follows a preexisting template.

**Comment by DominicDirkx** [comment]
Thanks for the suggestioon.

@ifodde: could you make the small modifications to the wiki?

**Comment by mfacchinelli** [comment]
Hi Dominic,

I am having some more trouble with the implementation. 

The first problem is that I need to normalize the quaternion to make sure the norm does not differ too much from 1, but I do not know where that statement should be. Right now I put it in `nBodyUnifiedStateModelWithQuaternionsStateDerivative.h` in the `convertToOutputSolution` function, but I have a feeling that is not the correct place. 

The second problem is that in the `calculateSystemStateDerivative` function, it seems like the `stateDerivative` contains Cartesian coordinates (since the last 3 elements are used as inertial accelerations), but then I overwrite them with the USM7 derivatives (which are 7 elements, instead of 6). Also, I added a print statement in the same function, and the accelerations are `nan`, whereas when I did the same with the Gauss equations (for Keplerian elements), they are all zeros. 

You can find the updated code at the same repository ([here](https://github.com/mfacchinelli/tudat)). And [this](https://github.com/Tudat/tudat/files/1886218/tudat.txt) is a text file with the output of the print statements.

Let me know if you need anything else, or if it is better to meet in person. 

Kind regards, 

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

I think this is best discussed in person, I can make some time for you tomorrow at 12:30. Would this suit you?

In the meantime, I see a few small issues:
- The code 'thinks' that the size of the state is 6, instead of 7. In nBodyStateDerivative.h, there is the code:

```
    int getStateSize( )
    {
        return 6 * bodiesToBeIntegratedNumerically_.size( );
    }
```

make this function virtual, so:
```
    virtual int getStateSize( )
    {
        return 6 * bodiesToBeIntegratedNumerically_.size( );
    }
```

and put 
```
    int getStateSize( )
    {
        return 7 * bodiesToBeIntegratedNumerically_.size( );
    }
```
in your usm state derivative class. I'm guessing that this is the cause of your ...e-153 variables.

Like I mentioned some time ago when we talked, I'm not sure if the fact that the state model you use and the Cartesian state having different sizes will have more consequences. Something we can discuss on Monday.

Concerning the normalization, this is something that is best handled at the level of the numerical integrator itself, we should discuss how best to implement this. For now, your approach is the best 'quick fix'.

For the accelerations, I'd advise calling sumStateDerivativeContributions with another (local) input vector, not stateOfSystemToBeIntegrated, I'm guessing the different size of the Cartesian/USM state will cause some issues here.

Have a nice weekend,

Dominic

**Comment by DominicDirkx** [comment]
By the way, what is the application you are using to generate your output?

**Comment by mfacchinelli** [comment]
Hi Dominic,

Thank you for the tips, I will implement them out now. I will see you today at 12:30 :)

**Comment by DominicDirkx** [comment]
This discussion is being continued on Gitter.
