### ISSUE TITLE
Tabulated Atmosphere with Multiple Independent Variables

### ISSUE THREAD

**Issue by mfacchinelli** [Tudat/tudat#376]
Hi Dominic, 

I have started working on the expansion of the tabulated atmosphere, to include more that 1 independent variables. You can find the changes I have made so far (which, by the way, are very limited) [here](https://github.com/mfacchinelli/tudat/tree/tabulatedAtmosphere). 

I have used the tabulated aerodynamic coefficient scripts as reference, since they also use multidimensional arrays. But I also noticed that the tabulated coefficients are also structured in quite a different way. 

So, I have some questions on how you I should structure this part:

- Should there be two different approaches for when only one independent parameter is selected? For instance, if only one is selected, then cubic spline is used, otherwise a linear n-dimensional interpolator is used?
- Should the independent variables be free? I don't really see the point in having an atmosphere only dependent on latitude (or anything not altitude). 
- There is also the problem that not only the number of independent variables are unknown, but also the number of dependent ones. 

Well, I have more questions, but they depend on whether what I have done so far is what you had in mind. 

Thank you for your help, once again!

Have a nice evening :)

**Comment by DominicDirkx** [comment]
Hi Michele,

Great to hear that you're starting to tackle this. To answer your questions (or at least give some ideas):

- Your approach would be perfectly suitable. An alternative approach would be to add InterpolatorSettings to the input, which can be used to interpolate the data. These could only be applied in the case of a single independent variable, though.
- I'd set the default independent variables to {altitude}, but leave any combination free to a user. You never know how people are going to use it. Also, and for you more importantly, writing the code in such a way that altitude _has_ to be an independent variable will probably be more cumbersome than making them entirely free.
- Where exactly is this a problem? I seem to recall having to do some template specialization stuff for the aerodynamic coefficients. If you can give some details on where/why exactly this becomes an issue, I can give some pointers,

Enjoy your evening,

Dominic

**Comment by mfacchinelli** [comment]
Hi Dominic, I just pushed the changes I have made so far. I'm not sure it's the most efficient way, but it should, after lots of debugging, (hopefully) work. I will write tonight or tomorrow a unit test, and try to build it. 

To solve the problem with the number of dependent variables, I created a new file, called `tabulatedAtmosphereReader.h`, which is pretty much the same as the aerodynamic coefficients counterpart, but accepts both the number of dependent and independent variables as template thingies. The problem was that for the aerodynamics, the number of dependent variables was fixed to 3 (drag, side, lift), whereas here, the user has freedom in choosing what he/she wants. Also, it spits out errors that use the word "atmosphere" instead of "aerodynamic". 

I have some doubts on the way I used the MultiLinearInterpolator, but I will see later if it gives problems. Right now I basically define it the same way the cubic spline interpolation was defined. So, instead of having:
```
interpolators::CubicSplineInterpolatorDoublePointer cubicSplineInterpolationForDensity_;
```
in private, I put this:
```
boost::shared_ptr< interpolators::MultiLinearInterpolator
            < double, double, numberOfIndependentVariables_ > > multiLinearInterpolationForDensity_;
```
where `numberOfIndependentVariables_` is also defined in private. If you have suggestions or if you know this is not going to work, let me know ;)

**Comment by mfacchinelli** [comment]
Ok, it would appear that one cannot use `numberOfIndependentVariables_` as template parameter. Also, it is not allowed to dynamically allocate a `boost::multi_array`. Should I create derived classes, based on the number of independent variables?

**Comment by mfacchinelli** [comment]
I solved the problem by using a template for the number of independent variables, but now the user has to manually add it as a template argument, which isn't really nice, especially since it could be simply extracted by taking the size of the independent variables vector. In fact, I was wondering if there was a way of creating a new class or constructor, such that this class calls the current tabulated atmosphere class with `independentVariables.size( )` as template. 

Another problem, is that the way it is currently done, the dependent variables need to be input in separate files. This is not really a problem if more that one independent variables are used, but is no longer compatible with the old tabulated atmosphere files. To solve this, is it better (or even allowed) to create a separate `initialize` function that accepts (only) 1 as template and carries out the same steps as the old tabulated atmosphere, or to simply have an if statement that runs the old code if only one independent variable is used, and the new code otherwise?

**Comment by DominicDirkx** [comment]
Hi Michele,

Looks like you've made good progress. Below, a few more suggestions for getting it to work:

- You now have:

interpolators::CubicSplineInterpolatorDoublePointer cubicSplineInterpolationForDensity_;

and

boost::shared_ptr< interpolators::MultiLinearInterpolator
            < double, double, numberOfIndependentVariables_ > > multiLinearInterpolationForDensity_;

You could also have 

boost::shared_ptr< interpolators::Interpolator
            < double, double, numberOfIndependentVariables_ > > interpolationForDensity_;

which can be either a one- or N-dimensional interpolator. Although this function only has a interpolate( std::vector< double > ) function, and no interpolate( double ), I think it's a small price to pay for making the code a bit more clean, since you wouldn't have any if/else statements for 1 or N-dimensional data, except when creating the interpolator,

**Comment by mfacchinelli** [comment]
Hi Dominic, 

I implemented the changes in the first answer, but it isn't clear to me how to incorporate the changes from the second answer. Should I create a new function called `createMultiDimensionalAtmosphereInterpolators( )`? But then would the output of this function still be of type `boost::shared_ptr< interpolators::Interpolator< double, double, numberOfIndependentVariables_ > >`? Or would it be overwritten (or rather, further specified) as a cubic-spline, or multi-linear, inside the new `createMultiDimensionalAtmosphereInterpolators` functions?

And these functions would need to go inside the `.cpp` file?

Thank you :)

**Comment by mfacchinelli** [comment]
I forgot one thing. I think that, however, the template would still be needed, because of how the dependent variable data is created. Right now it is declared to be of type `boost::multi_array< double, static_cast< size_t >( NumberOfIndependentVariables ) >`, and if I recall correctly, yesterday (when I was using `numberOfIndependentVariables_`, instead of the template), it was giving an errors saying that I could not use a 'non-static data member'.

**Comment by DominicDirkx** [comment]
A template argument will indeed still be needed somewhere in the code. However, you can restrict this template to a single function. For instance, it's fine to have the following member function:

template< int NumberOfIndependentVariables >
void createAtmosphereInterpolators( /// Input list of data files (?) // )
{
      // Load data files, assign to multi-arrays with size NumberOfIndependentVariables, create interpolators
}

In this way, the multi-arrays will only exist inside this function, where the MultiLinearInterpolator is created. However, since the Interpolator class does _not_ have a template argument for the size, the rest of the TabulatedAtmosphere class doesn't 'care' about this size.

I hope this helps, it's a more complicated construction than you would use in most other parts of the code, but it will allow a very general implementation with relatively simple interfaces.

**Comment by mfacchinelli** [comment]
Hi Dominic, thanks for the suggestion, but I can't manage to make it work. Right now the `initialize` function calls the `createAtmosphereInterpolators` function, which is declared like this:
```
template< int NumberOfIndependentVariables >
void createAtmosphereInterpolators( const std::vector< std::string >& atmosphereTableFile );
```
but gives the error saying 'no matching function fo call to createAtmosphereInterpolators, invalid explicitly-specified argument for template parameter'. The template input is `numberOfIndependentVariables_`, which is also an integer.

**Comment by DominicDirkx** [comment]
Hi Michele,

The problem is that you cannot put numberOfIndependentVariables_ as a template parameter, it _has_ to be defined during compile time, so it has to be an explicit number. Right now you have the function:

template< int NumberOfIndependentVariables >
void TabulatedAtmosphere< NumberOfIndependentVariables >::initialize( const std::vector< std::string >& atmosphereTableFile )

I think this should be:

void TabulatedAtmosphere::initialize( const std::vector< std::string >& atmosphereTableFile )

since the TabulatedAtmosphere class is not templated, and you don't yet know the NumberOfIndependentVariables when calling this function. You have:

int numberOfIndependentVariablesInFile = input_output::getNumberOfIndependentVariablesInCoefficientFile(
                atmosphereTableFile_.at( 0 ) );

which is exactly what you need for the next step, for which I posted an outline a couple of posts ago (with the switch statement). You'll need another function: one that actually reads the file contents and creates the interpolators, and it is only this _function_ that should be templated, so something like:

template< int NumberOfIndependentVariables >
void createMultiDimensionalAtmosphereInterpolators( .... )

Note that this function would need to be defined in the header file, as it's templated,

Good luck!

Dominic

**Comment by mfacchinelli** [comment]
Ok! I think I understand now. Thanks again for the help :) 
It does compile, but the unit test fails. I'll try to figure out what is going wrong

**Comment by mfacchinelli** [comment]
Hi Dominic, I have good news! It seems to be working now :) 
The unit test works fine, and I have also tested some cases with altitude, longitude and latitude. The linear interpolator also works fine. I am now seeing how it behaves when I shuffle (in)dependent variables around.

**Comment by DominicDirkx** [comment]
Hi Michele,

Units are meters, radians, and seconds since J2000. 

Right, I forgot about that. It shouldn't be too much work to extend it to 4 independent variables. Let me know if you'd like me to update this, or if you'll give it a try (if you need the feature),

**Comment by mfacchinelli** [comment]
I don't really need it, but I can take a look. From what I understand after a quick look at the `parseRawXDimensionalCoefficientsFromFile`s it seems like it should be relatively straight forward. 

Have a nice extended weekend :) 

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,


Very good, thanks! Indeed the 'bumps' are probably due to the linear interpolation. I doubt it's worth the effort, but you can consider implementing an N-dimensional spline interpolator:


https://arxiv.org/pdf/0905.3564.pdf


Good luck,


Cheers,


Dominic

________________________________
Van: Michele Facchinelli <notifications@github.com>
Verzonden: vrijdag 27 april 2018 11:23:33
Aan: Tudat/tudat
CC: Dominic Dirkx - LR; Comment
Onderwerp: Re: [Tudat/tudat] Tabulated Atmosphere with Multiple Independent Variables (#376)


Hi Dominic,

I added the support for four dimensional files. However I have not yet tested it. Two storage methods are supported, one with the forth dimension along the columns, and the other one along the rows, since I didn't really know which one would be best.

Also, I updated the unit test, so now it also checks for the multidimensional atmosphere. The file it uses are from the time-averaged tabulated atmosphere, which I created based on the Mars Climate Database.

I also tested the atmosphere during propagation, I don't think the difference in computation time is even noticeable, which is very nice :)
The only issue is that, as expected, the aerodynamic acceleration is a bit bumpy (probably, due to the linear interpolator that is being used). You can see that in the picture I attached. I will play around with the independent variable ranges, at some point, to see if the effect can be reduced.

Happy King's day!

Michele

untitled.pdf<https://github.com/Tudat/tudat/files/1954529/untitled.pdf>

**Comment by mfacchinelli** [comment]
Hi Dominic, 

I will take a look, but as you said, I am not sure it's worth the effort. 

I have fixed some bugs in the multi-array file reader, and now it works for both methods I listed above. I  also included two test files for the unit test, to test both methods, and expanded the unit tests for tabulated atmosphere.

**Comment by mfacchinelli** [comment]
Hi Dominic, 

As discussed with Erwin, I was trying to find where the interpolators decide what to do in case the independent variable is outside the range specified by the user, but I can't manage to find it. Do you know where it is? 

From what I understood, Erwin suggested there should be three modes to choose from: throw exception (default), extrapolation and using the closest available value. 

Thank you! 

Michele

**Comment by DominicDirkx** [comment]
Hi Michele, 

I just checked, and it seems that this is limited to the Lagrange interpolator only, and even there not all three options are available. If you open a separate issue on this, I'll try to get to it in the coming week.

Cheers,

Dominic

**Comment by mfacchinelli** [comment]
Ok, will do! Thanks

**Comment by mfacchinelli** [comment]
Hi Dominic, 

I was trying to compile all Tudat libraries, and I got a few errors related to the tabulated atmosphere. Turns out that the new file system (the user needs to input a map of files) is incompatible with the code written for the JSON interface (specifically lines 52 and 94 of [atmosphere.cpp](https://github.com/Tudat/tudat/blob/master/Tudat/JsonInterface/Environment/atmosphere.cpp)). I am don't really know how the JSON interface works, so I am not sure how (and if I should) tackle this. 

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

I think the best way to tackle this is to have a second constructor for the TabulatedAtmosphereSettings that gets the exact same input as in the old setup. This new constructor can then parse this input so as to be compatible with the updates to the TabulatedAtmosphereSettings class. For backwards compatibility, this would be very useful. If you want, you can also comment out the offending lines in the JSON interface, and we'll sort this out later,

Dominic

**Comment by DominicDirkx** [comment]
Hi Michele,

That's a good point, I hadn't thought about that.... 

Indeed, probably it's best to change the default boundary handing to something that _doesnt_ provide console output.

Dominic

**Comment by mfacchinelli** [comment]
Hi Dominic, 

I was a bit too quick in closing this issue. I noticed that soon after you merged the code by Iosto on the expanded tabulated atmosphere, where he included also information on the gas species. 

I was wondering whether I should keep the two atmosphere settings separate or if I should merge the two. I don't really need the species stuff, since I have already done some pre-processing of the MCD in MATLAB, but as you know, I don't mind spending extra time on programming :)

Let me know what you think,

Michele

**Comment by mfacchinelli** [comment]
Hi Dominic,

Never mind :) I just realized that the code you merged does not include the version of tabulated atmosphere that I was referring to. 

I'll reopen this issue when it will be actually needed. 

Michele
