### ISSUE TITLE
Save Accelerations when using double Direct tidal interactions

### ISSUE THREAD

**Issue by FloorMelman** [Tudat/tudat#392]
As discussed this morning, the implementation of the double tidal accelerations (both tides induced on the satellite and on the planet) is possible and gives no errors. However, errors are given when the attempting to save the tidal accelerations: _Error when getting acceleration between bodies Io and Jupiter of type 12, no such acceleration found_ What might a solution to mitigate this?

Furhtermore, when I get rid of the time interval at getDefaultBodySettings, it does not set Saturn as the barycenter of the body. Therefore no ephemeris data is available. Mitigating this by defining the body Saturn as the Saturn Barycenter does not work either as it requests a radius at that time. How can this issue be resolved?

**Comment by FloorMelman** [comment]
Link to the script:
https://github.com/FloorMelman/Thesis/blob/2018_05_28/thesis/thesis.cpp

**Comment by DominicDirkx** [comment]
HI Floor,

For the first point, the problem seems to be that there are two available options for the dissipative acceleration to be saved, and it cannot select the right one. A small modification to the code is required, open a dedicated issue on this, and I'll fix it in the coming week.

For the Saturn ephemeris, the easiest approach is to also load the saturn ephemeris into spice (or continue to use the one with the intermediate interpolator),

**Comment by DominicDirkx** [comment]
Addressed in issue #393
