### ISSUE TITLE
Error in Thrust Guidance

### ISSUE THREAD

**Issue by mfacchinelli** [Tudat/tudat#394]
Dear Dominic, 

When I try to run my application
https://github.com/mfacchinelli/tudatTesting/blob/master/propagatorsComparison.cpp
with `testCase` equal to 5, i.e., the simulation of a low-thrust trajectory, where the thrust is directed opposite to the velocity vector, I get the error

> Error, body-fixed frame to propagation frame not yet implemented for DirectionBasedForceGuidance.

However, when I run the example application `thrustAlongVelocityVectorExample.cpp`, all goes well. I can't really manage to see what I am doing wrong, especially since I basically copied the blocks of code I needed from the example. 

I also tried to use the `CustomThrustDirectionSettings`, with a fixed direction, but also that fails (with the same error).

Thank you!

Michele

**Comment by DominicDirkx** [comment]
Hi Michele,

It's not a bug, it's a feature :) 

The problem is that you are using a thrust model that is defined by the direction of the thrust vector, as opposed to the full rotation matrix from inertial to body-fixed frame. By defining the thrust direction in this manner, you have _not_ fully defined the rotation matrix: you can still rotate the body about the thrust vector, but this rotation has not been defined anywhere. Therefore, the rotation matrix (body-fixed to propagation frame) _cannot_ be computed. 

The best way to circumvent this, is to implement the function that now throws this error yourself, and setting the free angle to a default value (or computing it somehow),

Dominic
