### ISSUE TITLE
Problem using AdamBashforthMoulton integrator

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#409]
Dear all,
I have been trying to use AdamBashforthMoulton integrator set up in the parameter estimation process. When the integrator settings are passed into the OrbitDeterminationManager class, it results in a 'Segmentation fault'. Could you help me to solve this problem?

**Comment by DominicDirkx** [comment]
Hi Pugazh,

Just with this information, I cannot tell you anything. Since youre working on linux, you can easily generate a stack trace:

http://tudat.tudelft.nl/tutorials/troubleshooting/debuggers.html?highlight=backtrace#debugging-in-terminal

and find where the stack trace is occuring

Also, why do you _need_  the ABM?

Dominic

**Comment by Pugazhenthi-Sivasankar** [comment]
Hello Dominic, thank you for letting me know about the debugger for terminal option. However, I can't install it in the eudoxos server without knowing the root password.
