### ISSUE TITLE
Errors when executing step "Make", linux red hat 7.5

### ISSUE THREAD

**Issue by SebastianVillamil** [Tudat/tudat#420]
Hi,

running applications on our linux system red hat 7.5 fails with the message "Errors when executing step "Make"". We've already made sure that QT accesses recent cmake and compiler versions. Where could our problem lie?
Upon running the unit tests, the following ones failed:

31 - test_EmpiricalAccelerations (Not Run)
39 - test_RotationalEphemeris (Not Run)
41 - test_FrameManager (Not Run)
42 - test_CompositeEphemeris (Not Run)
43 - test_TabulatedRotationalEphemeris (Not Run)
45 - test_GcrsToItrsRotation (Not Run)
Errors while running CTest
gmake: *** [test] Error 8

[LastTestsFailed.log](https://github.com/Tudat/tudat/files/2263238/LastTestsFailed.log)
[LastTest.log](https://github.com/Tudat/tudat/files/2263240/LastTest.log)

Best regards
Sebastian

**Comment by DominicDirkx** [comment]
Hi Sebastian,

This is a rather strange error, since most unit tests are running and passing, but a few are not even being run. A few questions:

- Could you check if the tests that don't run are compiled (manually check in the bin folder)
- What is the version of Tudat you are working on (e.g what is the last commit that you have)?
- Are there any changes w.r.t. the repository that you've made.
- Which compiler are you using?
- Do the example applications compile/run?

**Comment by SebastianVillamil** [comment]
Hi Dominic,

- the files for the tests in question (test_EmpiricalAccelerations, test_RotationalEphemeris, etc) are within the bin folder. Their size is 0 bytes however.
- The tudat commit we are working with is the most recent one from the 26th of July
- We haven't made any changes
- The compiler we are using in the kits settings is GCC_updated. Its version is 4.8.5 20150623 (Red Hat 4.8.5-28)
- The application HelloWorld works fine, as does ApolloEntry and EarthOrbiterBasicStateEstimation. Upon trying to run the SingleSatellitePropagator, SinglePerturbedSatellitePropagator, the error we obtain reads "Failed to start program. Path of permissions wrong?"

**Comment by DominicDirkx** [comment]
My guess is that the compilation terminated prematurely, since some of the tests and applications don't seem to have (fully) compiled. 

Are you compiling through Qt or the terminal? Could you post the full compile output that you get in a text file?

How are you running each application? Are you ensuring that it compiles before you run it?

**Comment by SebastianVillamil** [comment]
Hi Dominic,

attached you will find both the compile output when building all and when only running SingleSatellitePropagator. I compiled using Qt
I just also tried compiling via the console, but all attempts failed with the error message "fatal error: Tudat/SimulationSetup/tudatEstimationHeader.h: No such file or directory". The mentioned file exists however. This also occurs for applications which function when compiled through Qt (e.g. apolloCapsuleEntry.cpp)
Hope that helps!

[compile_build.txt](https://github.com/Tudat/tudat/files/2311437/compile_build.txt)
[compile_SingleSatellitePropagator.txt](https://github.com/Tudat/tudat/files/2311438/compile_SingleSatellitePropagator.txt)

**Comment by DominicDirkx** [comment]
Hi Sebastian,

The output looks as it should, so that's good. Try deleting the executables for the tests that are 'Not Run', and recompile. If that doesn't work, try compiling only one of these executables.

Which command, and in which directory, are you compiling from terminal? What do you mean with your sentence 

'This also occurs for applications which function when compiled through Qt (e.g. apolloCapsuleEntry.cpp)"

Could you post the full compile output?

**Comment by SebastianVillamil** [comment]
Hi Dominic,

I deleted the faulty executables (both for the applications and the tests) and tried to rebuild all libraries. Upon doing so the compilation did not finish and I got the following compile output:
[CompileOutput_build.txt](https://github.com/Tudat/tudat/files/2313738/CompileOutput_build.txt)
Upon running the tests the following one:
[CompileOutput_tests.txt](https://github.com/Tudat/tudat/files/2313743/CompileOutput_tests.txt)
And for the applications SingleSatellitePropagator and SinglePerturbedSatellitePropagator:
[CompileOutput_SinglePerturbedSatellitePropagator.txt](https://github.com/Tudat/tudat/files/2313747/CompileOutput_SinglePerturbedSatellitePropagator.txt)
[CompileOutput_SingleSatellitePropagator.txt](https://github.com/Tudat/tudat/files/2313748/CompileOutput_SingleSatellitePropagator.txt)
The application apolloEntry which worked previously no gives the following errors in the compile output:
[CompileOutput_apolloEntry.txt](https://github.com/Tudat/tudat/files/2313753/CompileOutput_apolloEntry.txt)

Here also the log file when compiling tudat applications "make all" from the console
[log_make.txt](https://github.com/Tudat/tudat/files/2314322/log_make.txt)

I'm guessing the problems arise due to some misconfigurations on Qt, as the applications (SingleSatellitePropagator, SinglePerturbedSatellitePropagator) work fine after having compiled them through the console. Once we compiled them through the console, running the applications through the console in the bin folder and through Qt worked out fine.
The tests, which we haven't yet compiled through the console still fail to compile.

**Comment by SebastianVillamil** [comment]
Hi Dominic,
unfortunately that didn't solve our problem. We did manage to get tudat to work now. Apparently, the compiler was not always accessing the most recent version of cmake. Having fixed that, and using the most recent build all unit test ran successfully!
