### ISSUE TITLE
Failed unit tests after installation

### ISSUE THREAD

**Issue by ThomasHaex** [Tudat/tudat#461]
Hello Github support,

I have some troubles after installing my Tudat. I started already having QT Creator from last year, but installed a completly new folder with the tudat_shell.bat file. This worked fine and I could start building Tudat.

The building worked out to quite some extent. I got 32 warnings, of which I included a screenshot.

But when running the unit tests, I did not succeed completely. 6 of the unit test failed, of which I put the result in a text file. Also I included my start up messages of Tudat in another text file.

Is my current Tudat installation sufficient for the coming excersises or should I do something different, and if that is the case how do I do something different?

Best regards,

Thomas Haex

[Tudat Start Messages.txt](https://github.com/Tudat/tudat/files/2581652/Tudat.Start.Messages.txt)
[Tudat Unit Test Result.txt](https://github.com/Tudat/tudat/files/2581673/Tudat.Unit.Test.Result.txt)

![tudat installation issues](https://user-images.githubusercontent.com/15799651/48496708-e69f2b80-e832-11e8-8914-28ee2f3518bf.PNG)

**Comment by DominicDirkx** [comment]
Hi Thomas,

Your unit test failures are, I think, due to the fact that you're still using the old Mingw 5.3.0 compiler, instead of the newer Mingw 7.3.0 compiler. The new one was only made available in Qt recently, and last year we had to make do with 5.3.0.

Since there is a new compiler, we are no longer supporting the old one. Based on your unit test failures, I think everything you need for Numerical Astrodynamics is working fine, but I cannot guarantee it. You can choose to either continue as is, or reinstall Qt (with Mingw 7.3.0) and recompile.

Dominic

**Comment by ThomasHaex** [comment]
Hello Dominic,

Good to know. In that case I will start over again and let you know if it worked out. Just to be sure. Thanks for the response!

Best regards,

Thomas
