### ISSUE TITLE
Request to create a single-arc multiple drag coefficient estimation functionality.

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#505]
Hello everyone,
I am working on the POD of GRACE and PROBA satellites using TUDAT. I am using externally provided GPS state vector data of the satellites as observables. The state vector data are available as separate files for each day. Currently, I am able to estimate one drag coefficient (Cd) per file which translates to one Cd per day. When I want to estimate more than one Cd per day, I split the external file accordingly. But this reduces the arc length of the POD and beyond 3 splits per day, I start to get negative values for Cd. I checked the TUDAT Doxygen documentation and it provides only one constant Cd estimation per single-arc scenario. Hence, I need a functionality in TUDAT that estimates multiple Cds for one single arc (i.e.) without reducing the arc length.

Thanks in advance!

**Comment by DominicDirkx** [comment]
Hi Pugazh,

We've updated the code with this feature:

https://github.com/DominicDirkx/tudat/tree/ArcwiseDragEstimation

Before pulling the new code, make sure to locally commit your current version of Tudat, so that you can easily go back to what you have now in case there are many merge conflicts. 

Dominic

**Comment by DominicDirkx** [comment]
Unit test has been added, and code merged into Tudat master:

https://github.com/Tudat/tudat/pull/517
