### ISSUE TITLE
spaceX Tesla Roadster Trajectory error in bulrisch stoer integrator

### ISSUE THREAD

**Issue by wcyoung08** [Tudat/tudat#526]
Hi, so when I try and run the tesla roadster trajectory example application, I get the error: `Error in numerical integrator. The function to modify the current state has not been implemented in this integrator.` The code for the Bulrisch Stoer integrator looks like this:

```
std::shared_ptr< IntegratorSettings< > > integratorSettings
            = std::make_shared< tudat::numerical_integrators::BulirschStoerIntegratorSettings< > >(
                simulationStartEpoch, 3600.0,
                numerical_integrators::bulirsch_stoer_sequence, 4,
                std::numeric_limits< double >::epsilon( ), std::numeric_limits< double >::infinity( ),
                1.0E-15, 1.0E-12 );
```
Thanks for any help you can give.

**Comment by mchambe** [comment]
Dear William,
The error you get is likely to come from the fact that USM propagators cannot be used along with Burlisch-Stoer integrator (because of potential singularities that might occur). Do you indeed use one of these USM propagators? If it is the case, you will have to change either your integrator or propagator, as Tudat is not able to use them simultaneously.

Best regards,
Marie

**Comment by wcyoung08** [comment]
Hi Marie, thanks for the response.
I don't think that is the problem. The propagator used initially was cowell, but I changed it to encke just to see if that would work, and I got the same error. Here's the code snippet just so you can confirm.
```
// Propagator Settings
    std::shared_ptr< TranslationalStatePropagatorSettings< double > > propagatorSettings =
            std::make_shared< TranslationalStatePropagatorSettings< double > >
            ( centralBodies, accelerationModelMap, bodiesToPropagate, teslaRoadsterInitialState, simulationEndEpoch, encke,
              dependentVariablesToSave );
```

**Comment by mchambe** [comment]
Dear William,

Sorry, my mistake, I did not see it was a sample application so I actually had access to the code (my TudatExampleApplications repository was not up to date). Indeed, it has nothing to do with the propagator in your case.
It is actually an error that has occurred before and the code has been updated since then to fix it. Can you try updating your code and tell me if it works? 

(Especially, among others, I think the following lines of code are currently missing in your Tudat/Mathematics/NumericalIntegrators/bulirschStoerVariableStepsizeIntegrator.h file:
https://github.com/Tudat/tudat/blob/master/Tudat/Mathematics/NumericalIntegrators/bulirschStoerVariableStepsizeIntegrator.h#L389-L397 )

Marie

**Comment by wcyoung08** [comment]
That fixed it! I have it working now. Thanks

**Comment by mchambe** [comment]
Happy to hear it! 
Best,
Marie
