### ISSUE TITLE
Setting up tidal acceleration on an orbiter

### ISSUE THREAD

**Issue by SebastianVillamil** [Tudat/tudat#549]
Hi everyone,

how can I extend my simulation environment to include the effect of tidal forcing on a satellite (k_2) on an orbiter which is orbiting said satellite? I.e. how do I set up a gravity field variation due to tidal forcing?

Kind regards
Sebastian

**Comment by DominicDirkx** [comment]
Hi Sebastian,

You can have a look at this unit test:

https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/OrbitDetermination/UnitTests/unitTestTidalPropertyEstimation.cpp#L333

It tests the estimation of Earth Love numbers.

First, you need to provide gravity field variation settings, like is done here:

https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/OrbitDetermination/UnitTests/unitTestTidalPropertyEstimation.cpp#L354

in your case, you only have one variation: degree 2 variations due to Jupiter only.

You don't need to change _anything_ about the acceleration settings. Using these gravity field variations, the tides are taken into account in the spherical harmonic coefficients

Estimation of teh Love numbers is done here:

https://github.com/Tudat/tudat/blob/master/Tudat/Astrodynamics/OrbitDetermination/UnitTests/unitTestTidalPropertyEstimation.cpp#L421-L428

Which you can replace with:

parameterNames.push_back( std::make_shared< FullDegreeTidalLoveNumberEstimatableParameterSettings >(
                                  "Ganymede", 2, "Jupiter", false ) );

For the estimation of a single, real, k2 Love number,

Best,

Dominic
