### ISSUE TITLE
Returning a TUDAT_NAN or similar from a failed root finding call instead of a runtime_error

### ISSUE THREAD

**Issue by gdominguezcala** [Tudat/tudat#550]
Hi all.

Im using tudat root finders and I am running into an issue when calling it. I am expecting to obtain a failed convergence as a function (a trim function) fails to find a root. When this happens, a nan is inserted in the function (after an infinity from the previous call), and I would like the root finder to know this and automatically stop without a runtime_error, that is, returning a nan or something similar I could detect and continue running the code (I would then try with a different root finder, or would just store it as a failed try). 

Currently the runtime error comes because it reaches a maximum number of iterations.
[applicationOutput.txt](https://github.com/Tudat/tudat/files/3284901/applicationOutput.txt)

Do you know how I could fix this?

Regards, 
Guillermo

*the error comes from the function in my repo sphynxAerodynamicDatabase.cpp line 413 (when the first root finder is called)

**Comment by kartikkumar** [comment]
Exceptions are a contentious issue in the C++ community. For historical/legacy reasons, we chose to implement runtime errors for violation of conditions like this instead of the old "flags" approach that's used in C code often to return status (akin to returning TUDAT_NAN or something else).

The right way to continue your simulation with the runtime exception implemented is to use a try-catch block. It's explained pretty succinctly in this SO thread: https://stackoverflow.com/questions/7491877/c-catch-runtime-error

**Comment by gdominguezcala** [comment]
Thank you! it is working now.
