### ISSUE TITLE
Aerodynamic coefficients cause warning (DirectionBasedForceGuidance)

### ISSUE THREAD

**Issue by wjhuisman** [Tudat/tudat#554]
Hi,

When adding my aerodynamic coefficients, I get the warning:
`Warning, body-fixed frame to propagation frame not yet implemented for DirectionBasedForceGuidance. The function will return a unit rotation to represent the rotation from body-fixed to inertial frame.`

I followed the same method as in the `singlePerturbedSatellitePropagator.cpp` file. Does this occur due to a wrong combination of a thrust vector and aerodynamic acceleration?

I set my aerodynamic coefficients here: [https://github.com/wjhuisman/Thesis_WJ_Huisman/blob/ad08a353e6ace8f7d6578437c41849c51c122df7/headers/header_imports.h#L152](url), and I add my accelerations here: [https://github.com/wjhuisman/Thesis_WJ_Huisman/blob/ad08a353e6ace8f7d6578437c41849c51c122df7/headers/header_imports.h#L207](url).

I run the code in this file: [https://github.com/wjhuisman/Thesis_WJ_Huisman/blob/master/sources/validationAnalysis.cpp](url)

Thanks in advance!

**Comment by DominicDirkx** [comment]
Hi Wouter,

You are using both a thrust acceleration, and an aerodynamic acceleration. In general, both of these accelerations require the vehicle's orientation to be known. In your setup, you define the vehicle orientation through the thrust settings through:

shared_ptr<ThrustDirectionGuidanceSettings> thrustDirectionSettings = make_shared<ThrustDirectionFromStateGuidanceSettings>("Earth", true, false);

However, this does not fully fix the vehicle's orientation, only the two degrees of freedom that the thrust acceleration needs (the third degree of freedom, rotation of the vehicle's body-fixed frame around the thrust vector, is not defined by these settings). 

The warning that is printed indicates that, for any model _other than the thrust_ that requires the body-fixed<->inertial rotation matrix, an identity matrix is used (which is not the best solution, as it also does not adher to the 2 degrees of freedom that _are_ defined). For you, however, I don't think this matters, since you have a constant-coefficeint drag-only aerodynamic model. This model is define without the need for the orientation of the body. So, I think it's safe to ignore thsi warning, but be aware that any result that depends explicitly on the orientation of your vehicle's body-fixed frame will be incorrect,

Dominic

**Comment by wjhuisman** [comment]
Thanks for your help!
