### ISSUE TITLE
Tudat version from last year 

### ISSUE THREAD

**Issue by JoanaLisa** [Tudat/tudat#577]
Hi Dominic and Kevin,
Since I installed Tudat already last year, I was wondering if there are special instructions on how to update it for this year. Or is the only way to reinstall it? 
I'd appreciate any tips and tricks :)
Looking forward to the course. 

Best,
Joana

**Comment by DominicDirkx** [comment]
Hi Joana,

You should be able to keep the same programs (Qt, CMake, etc.). However, I would recommend you reinstall tudatBundle from scratch, starting here:

https://tudat.tudelft.nl/installation/downloadTudatBundle/index.html

Which operating system are you using?

We have made numerous modifications to the code, and updating each submodule independently is possible, but very error prone. Unfortunately, due to the large number of students, this is a process that we have chosen not to support for this year. 

Best,

Dominic

**Comment by JoanaLisa** [comment]
Hi Dominic,

Ok perfect. I'll do that then. Thanks.
I'm using Windows 10.  Sorry for not mentioning this earlier, forgot.

Best,
Joana

**Comment by DominicDirkx** [comment]
No worries, make sure that your com
