### ISSUE TITLE
Step 3.3 error: No CMAKE_C_COMPILER could be found

### ISSUE THREAD

**Issue by PaulPerez6** [Tudat/tudat#586]
Hi,

I am using Mac OS 10.13, and am having problems with step 3.3 of the installation. After opening the main project file CMakeLists.txt and configuring the project with the default settings, I get the following error: [GeneralMessagesError.txt](https://github.com/Tudat/tudat/files/3851821/GeneralMessagesError.txt)
It seems that the C and C++ compilers are maybe misplaced?

When looking at the Troubleshooting section 6, this error is mentioned. However, when going in the QtCreator Preferences, what is displayed (in the screenshot below) is not the same as in the Troubleshooting  section.

![QtCreatorPreferences Mac](https://user-images.githubusercontent.com/57774294/68949873-49673200-07bb-11ea-9593-46d53899ba5e.png)

I thus don't really know how to fix this,
Thanks in advance!

**Comment by DominicDirkx** [comment]
Hi,

Try looking under 'Kits', that may show you the screen you need,

Best,

Dominic

**Comment by transferorbit** [comment]
Hello @PaulPerez6,

Have you solved this issue yet? I can confirm that I successfully installed tudat with the default settings on macOS 10.15.1 (and 10.14). You _should not_ have to manually edit the `CMakeLists.txt` file, for example.

If you still have trouble, check whether you have the xcode command line tools installed (you should not have to install the entire xcode app; it’s huge) by entering the following on the terminal command line:
    `xcode-select --install`
If the xcode command line tools are installed properly, this should produce the following output:

    xcode-select: error: command line tools are already installed, use "Software Update" to install updates

If and when the xcode command line tools are installed, check that there are no updates for it, which you do via macOS: _System Preferences_ > _Software Update_

Otherwise let us know your issue is solved by closing it here in GitHub -or- report further details related to this particular issue in this thread.
