### ISSUE TITLE
Effect of Ephemeris Frame Origin on Propagated State

### ISSUE THREAD

**Issue by gmonechi** [Tudat/tudat#591]
As mentioned during the lecture, I found that my JUICE propagated state results are affected significantly by the Ephemeris Frame Origin when propagating with Jupiter as center of propagation. You can test this by running "juicePropagationQ5a.json" with different Ephemeris frame origin in my private repository (https://github.com/gmonechi/NumericalAstrodynamics2019_Guido_Monechi).

**Comment by DominicDirkx** [comment]
For this particular case, the cause is due to a very strong sensitivity on the initial conditions. Due to some rounding errors, there is a very small (sub-mm) difference in initial state, which causes the divergence of the two solutions.

Dominic

p.s. In hindsight, this is a question that would have been better suited to the Brightspace forum
