### ISSUE TITLE
Invalid sizes when resizing a matrix or array. Eigen Vector Error

### ISSUE THREAD

**Issue by RajathPai95** [Tudat/tudat#601]
The Error messsge reads 
_Assertion failed!

Program: D:\tudatBundle\tudatApplications\bin\applications\application_simulation.exe
File: D:/tudatBundle/eigen/Eigen/src/Core/PlainObjectBase.h, Line 285

Expression: (!(RowsAtCompileTime!=Dynamic) || (rows==RowsAtCompileTime)) && (!(ColsAtCompileTime!=Dynamic) || (cols==ColsAtCompileTime)) && (!(RowsAtCompileTime==Dynamic && MaxRowsAtCompileTime!=Dynamic) || (rows<=MaxRowsAtCompileTime)) && (!(ColsAtCompileTime==Dynamic && MaxColsAtCompileTime!=Dynamic) || (cols<=MaxColsAtCompileTime)) && rows>=0 && cols>=0 && "Invalid sizes when resizing a matrix or array."_

This is a runtime error which I've isolated to this part of my code

https://github.com/RajathPai95/MDAOThesis/blob/Inspection/Simulator/simulator.cpp#L480-490

I'm trying to store values returned in an std::vector to an Eigen::VectorXd.  I'd appreciate some insight into what is possibly wrong, why it's wrong and if there's a better way to store data from a std::vector to an Eigen::VectorXd 

Thank you,

**Comment by DominicDirkx** [comment]
Hi Rajath,

I'm assuming that your problem is in one of these lines:

https://github.com/RajathPai95/MDAOThesis/blob/Inspection/Simulator/simulator.cpp#L488-L490

can you confirm this?

I've never used the command you are using here, so I cannot comment on their correctness. You could do the conversion manually, or have a look at the Tudat/Basics/utilities.h file, where there are a bunch of useful conversion functions,

Best,

Dominic

**Comment by RajathPai95** [comment]
Hey Dominic,

Yes, I also think that those 3 lines are what's possibly creating issues. I too have no idea on their correctness as well. They were suggested on stack overflow. I'll have a look at the file and see if I find anything useful. I'll close this issue for now then.
Thanks,


Regards,
Rajath
