### ISSUE TITLE
Problems with building Pagmo Examples

### ISSUE THREAD

**Issue by jasperwolfhagen** [Tudat/tudat#604]
Hi,

I get an error message when building the Pagmo Examples, I saw there was an earlier issue on this and was wondering whether it is something I can fix. If I disable pagmo before building, it works.

I have Xcode 11.3 commandline on MacOs 10.15.1

Kind regards,
Jasper Wolfhagen

[erroroutput.txt](https://github.com/Tudat/tudat/files/4054121/erroroutput.txt)

**Comment by DominicDirkx** [comment]
Hi Jasper,

Can you verify that your tudat is up to date with the latest version?

Dominic

**Comment by jasperwolfhagen** [comment]
Hi,

I’ve downloaded the tudatBundle today, so does that mean that it is immediately up-to-date?

Met vriendelijke groet,
Jasper Wolfhagen

**Comment by DominicDirkx** [comment]
Hi Jasper,

Not necessarilly, but in this case I think you do. Ill forward your question to Elmar, ou Tudat TA, who has worked on our Pagmo interface in the past,

Best,

Dominic

**Comment by elmarputs** [comment]
Hi Jasper,

I will try to reproduce your error, as far as that is possible on Linux. In the meantime, I have one question: your error file seems to use Windows path names and executables (.exe), and the Qt kit in use is one that is only suitable for Windows 64 bit systems. However, from your post, I understand that you are using macOS; is this indeed the case? Because then we might have to look into your CMake/Qt configuration.

Best,

Elmar

**Comment by jasperwolfhagen** [comment]
Yes this is the case! Does this mean I ve dowloaded a QT version for Windows? I did use -j4 for building
Maybe its worth noting that if I do not builde pagmo, tudat works without a problem

Met vriendelijke groet,

Jasper Wolfhagen

**Comment by elmarputs** [comment]
The errors in your file are link errors and given the nature of those, it looks there is some binary incompatibility between your libraries and the executable you are trying to build. I think this is indeed the result of a misconfiguration. Did you build all libraries on your system with the same compiler? If not, I would recommend deleting all binaries (i.e. executables, libraries and the build folder) and recompiling the whole bundle.
The reason why it works with Pagmo switched off, is that CMake does not need to build new executables. As soon as Pagmo is built, Tudat also compiles some other example applications which might now be incompatible with the already built libraries.

I hope this was helpful!

Elmar

**Comment by elmarputs** [comment]
Could you perhaps also upload a screenshot of your Qt/Xcode configuration? That way, we may find if there is an inconsistency in your toolchain!

**Comment by jasperwolfhagen** [comment]
_If not, I would recommend deleting all binaries (i.e. executables, libraries and the build folder) and recompiling the whole bundle._ --> I do not fully understand this directive, do you mean to simply delete all of Tudat, redownload and install. I shall do that tomorrow then.

Below I have uploaded the screenshots, are these sufficient?:
<img width="1108" alt="Screenshot 2020-01-14 at 16 14 45" src="https://user-images.githubusercontent.com/33684647/72356294-533ce100-36e9-11ea-939d-cce5e5f0e7ff.png">
<img width="1106" alt="Screenshot 2020-01-14 at 16 14 28" src="https://user-images.githubusercontent.com/33684647/72356295-53d57780-36e9-11ea-9068-e27b242f520f.png">

**Comment by elmarputs** [comment]
Thank you for the screenshots. Could you also upload one of the 'Kits' tab, with the current kit selected (such that it shows the compilers etc.)? In that way, I can see if CMake uses the correct tools.

Regarding your first question: redownloading the whole bundle would be the last resort, so I would not do that until strictly necessary. For now, what you can do in Qt is clicking on Build->Clean all. This will remove all executables/libraries so that CMake will build them again next time.

**Comment by jasperwolfhagen** [comment]
<img width="1582" alt="Screenshot 2020-01-14 at 17 18 05" src="https://user-images.githubusercontent.com/33684647/72361582-027db600-36f2-11ea-807e-8849b99bbcad.png">

**Comment by elmarputs** [comment]
First of all, my apologies for the late reply; I could not do so due to illness.
What you could try is setting the two compilers in the kit settings to the **x86 64bit** versions of the executables, followed by a rerun of CMake and compilation of the applications you want to run. If that still does not work, I am afraid you have to compile all binaries with this new setting, as there might be some inconsistencies left across your files. In that case, perhaps the most straightforward way is to completely remove your Tudat bundle (make sure you have a backup of your own applications!) and to reinstall it afterwards.

Hope this helps,

Elmar

**Comment by jasperwolfhagen** [comment]
Thanks for the great support, ill try that and let you know!

Met vriendelijke groet,

Jasper Wolfhagen

**Comment by jasperwolfhagen** [comment]
Dear Elmar,

I've rebuild as you suggested the tudatBundle wit the kit settings all at x86 64bit. However, I keep getting an error message when buidling one of the example applications for Pagmo. I've added the compile output and some screenshots concerning the configuration settings. 
<img width="657" alt="Screenshot 2020-02-09 at 20 45 12" src="https://user-images.githubusercontent.com/33684647/74108707-55298100-4b7d-11ea-8526-e4b2bd82718b.png">
<img width="652" alt="Screenshot 2020-02-09 at 20 45 04" src="https://user-images.githubusercontent.com/33684647/74108709-56f34480-4b7d-11ea-8c6d-634653421547.png">
<img width="653" alt="Screenshot 2020-02-09 at 20 44 55" src="https://user-images.githubusercontent.com/33684647/74108710-578bdb00-4b7d-11ea-9bf9-47998aac0843.png">
<img width="644" alt="Screenshot 2020-02-09 at 20 44 50" src="https://user-images.githubusercontent.com/33684647/74108711-58247180-4b7d-11ea-8375-662abde68c3a.png">
<img width="516" alt="Screenshot 2020-02-09 at 20 44 42" src="https://user-images.githubusercontent.com/33684647/74108712-58bd0800-4b7d-11ea-8bc7-e00dd4905040.png">
[ErrorPagmo.txt](https://github.com/Tudat/tudat/files/4177643/ErrorPagmo.txt)

**Comment by jasperwolfhagen** [comment]
FYI: I've outcommented the specific 2013cec Pagmo example application from the cmake list in the Pagmo library and now it has built and runs smoothly. It appears as if it was only that specific example

**Comment by DominicDirkx** [comment]
Hi Jasper,

We'll try to get to this in the coming week,

Dominic

**Comment by jasperwolfhagen** [comment]
Thank you. 

An additional question:
I've set up a problem according to pagmo instruction. However, when I try to build islands or archipel it crashes. I've added the files in the attachment and the application output. As can be seen, if I call the problem and apply .fitness(decision varable) an accurate value is returned in the application output. Therefore, I have the idea that the problem does not lie with my program. Furthermore, I read on the Pagmo documentation that TBB is mandatory, while in the building process I disabled USE_TBB since it caused problems. Might this be the issue? BasicOptimisation.cpp is the main file.

Jasper Wolfhagen


[untitled folder 2.zip](https://github.com/Tudat/tudat/files/4210525/untitled.folder.2.zip)
[CompileOutput.txt](https://github.com/Tudat/tudat/files/4210531/CompileOutput.txt)
<img width="1200" alt="Screenshot 2020-02-16 at 19 16 06" src="https://user-images.githubusercontent.com/33684647/74610162-020d7c00-50f1-11ea-987f-24484840210f.png">

**Comment by elmarputs** [comment]
Hi Jasper,

I've run your application using a debugger and line 75 in ManeuverApplication.cpp: 
`Eigen::Matrix3d R_ric_xyz = reference_frames::getInertialToRswSatelliteCenteredFrameRotationMatrix(stateAtThrusting).transpose();`
seems to be the problem. Eigen gives quite an obscure error there (invalid sizes when resizing matrix or array), for which I do not have solution yet. I will keep you posted!

Elmar

**Comment by jasperwolfhagen** [comment]
Hi Elmar, 

Bedankt voor de moeite, ik had een verkeerde inschatting van waar het probleem ligt; de decision variable kan bij mij alleen verwerkt worden op het moment dat het een een afgerond getal, maar het algoritme kiest er een in decimalen. Dank!

**Comment by jasperwolfhagen** [comment]
Hi Elmar,

I've added a round statement in basicOptimisationProblem.cpp, where I assign the decisionvector. Now it first produces results for severeal times, but then returns the error below.  How can I handle this?

Decision variable: 11574.672    Fitness:22968.289
epochThrusting
5356
Decision variable: 5356.1037    Fitness:42570.281
epochThrusting
7327
Decision variable: 7327.1018    Fitness:35819.421
epochThrusting
960
epochThrusting
5083
SPICE(NAMESDONOTMATCH)
SPICE(NAMESDONOTMATCH)
CHKOUT:  Caller is EUL2M; popped name is EUL2M.
CHKOUT:  Caller is SXFORM; popped name is EUL2MSPICE(NAMESDONOTMATCH)
CHKOUT:  Caller is EUL2XF; popped name is SXFORM.
SPICE(NAMESDONOTMATCH)
CHKOUT:  Caller is TISBOD; popped name is sxform_c.
SPICE(NAMESDONOTMATCH)
CHKOUT:  Caller is FRMGET; popped name is EUL2XF.
SPICE(NAMESDONOTMATCH)
T; popped name is EUL2XF.

NAMESDONOTMATCH)
SPICE(NAMESDONOTMATCH)
CHKOUT:  Caller is FRMCHG; popped name is TISBOD.
SPICE(NAMESDONOTMATCH)
CHKOUT:  Caller is SXFORM; popped name is FRMGET.
M; popped name is FRMGET.

NAMESDONOTMATCH)
SPICE(NAMESDONOTMATCH)
SPICE(NAMESDONCTMATCHKOUT:  Calle
SPICE(NAMESDONCTMATCHKOUT:  Calle
is sxform_c; popped name is SXFORM.
CHKOUT:  Caller is sxform_c; popped name is SXFORM.
11:38:08: The program has unexpectedly finished.
11:38:08: The process was ended forcefully.
11:38:08: /Users/Jasper/Documents/GitHub/collision-avoidance/tudatExampleApplications/templateApplication/bin/applications/application_basicOptimisation crashed.

**Comment by elmarputs** [comment]
Hi Jasper,

Good to hear you solved the first problem!
The Spice errors are likely due to the fact that you are running your optimization in parallel (Pagmo archipelago). Spice is a so-called thread-unsafe library which means that multiple instances of your problem can access Spice at the same time, possibly messing up internal variables.

I've had this problem as well, and my best guess is that it occurs because of the rotational ephemeris that is retrieved from Spice. The solution would be to create an interpolated ephemeris based on a table. I see you already did this for the translational case, but I don't know if this feature has already been implemented in Tudat for the rotational ephemeris. Perhaps @DominicDirkx can help you with this issue, as he knows more about this.

In the meantime, you could test your program with a single island. I know it is suboptimal but for now, I do not really see an alternative.

Elmar

**Comment by DominicDirkx** [comment]
Hi Jasper,

I agree with Elmar, that this is due to multithreading using Spice. 

Please push your code to a repository (public or private, if private please invite both Elmar and myself), indicate the place(s) in the files where you create body object(s) that are used in the optimization loop, and I'll have a look,

Dominic

**Comment by jasperwolfhagen** [comment]
Thanks for the quick answer. As Elmar suggested I've decreased the number of islands to one and the error does not occur and the algorithm works as expected. 

I've invited you both to a private repository with the files, thanks again

**Comment by DominicDirkx** [comment]
Hi Jasper,

Please, also address the second part of my last response, so that we know where to look,

Dominic

**Comment by jasperwolfhagen** [comment]
I'm sorry, I thought the comments would also be shown in the repository. In the lines 30-70 of the file basicOptimisationProblem.cpp the bodies are defined and created. Note that two bodymaps are created here:
1) A bodymap containing two satellites which are propagated one full time including their STM's.
2) A bodymap containing the satellite of interested which is propagated multiple times since different maneuvers are applied in the optimisation procedure.

Jasper

**Comment by DominicDirkx** [comment]
Hi Jasper,

Thanks, that's clear. I hope the solution will be fairly straightforward, try replacing this line:

https://github.com/jasperwolfhagen/thesisProject/blob/master/basicOptimisationProblem.cpp#L37

with:

    
```
    bodySettings[ "Earth" ]->rotationModelSettings = std::make_shared< SimpleRotationModelSettings >(
                "J2000", "IAU_Earth", spice_interface::computeRotationQuaternionBetweenFrames(
                    "J2000", "IAU_Earth", simulationStartEpoch_ ),
                simulationStartEpoch_, 2.0 * mathematical_constants::PI / physical_constants::SIDEREAL_DAY );
```

I think this will solve (part of?) your problem. If the problem persists, could you post the lines where you create the BasicOptimisationProblem objects?

Best,

Dominic

**Comment by jasperwolfhagen** [comment]
Hi Dominic, 
Unfortunately there is still an error, although different than previously, see Screenshot. I've updated the repository and the objects are created in those same lines 80 -82 in basicOptimisationProblem.cpp
![Screenshot 2020-02-19 at 17 14 41](https://user-images.githubusercontent.com/33684647/74851300-59069180-533b-11ea-817a-0932626eb81d.png)

**Comment by DominicDirkx** [comment]
Hi Jasper,

This seems like the Spice error has indeed been fixed, which is good. Please investigate in a bit more detail where the issue occurs, specifically at which point the code seems to crash. Once you have this narrowed down, please post it here, and also briefly explain all the steps the code goes through before the crash. Finally, check to see if your RAM is not maxing out just before the crash,

Best,

Dominic

**Comment by jasperwolfhagen** [comment]
Hi Dominic, 

I've firstly checked to see if the RAM but from activity monitor on my Mac it appears as this is not the issue as part of my laptop is idle while running, see attached gif.

I've performed the following steps in debugging: 
1) Run the optimisation for one island in the archi class for the sade algorithm
-> No issue appears. 
2) Run the optimisation several times for two islands in the archi class for the _sade_ algorithm
--> Issues keep appearing at epoch of thrusting 2970 or 6650 when the singlearcsdynamicsimulator (_dynamicsSimulatorBeforeBurn_) object is created for the first time within the ManeuverApplication.cpp class. All inputs to the singlearcsdynamicsimulator object appear to have sizes as expected and to all the previous evaluations. 
3) Run the optimisation several times for two islands in the archi class for the _de1220_ algorithm. 
--> Issues keep appearing at epoch of thrusting 16296 or 17773 at the same point in the ManeuverApplication.cpp class when the single arc dynamics simulator is called (_dynamicsSimulatorBeforeBurn_). 

To me, it appears as if the issue is not with any of the specific epochs, since all variables that are printed and derived from it do not show any deviation. Also they are different between the two algorithms.
The creation of the dynamicsSimulatorObject seems to be problematic, but it is odd that this does not pose an issue in the one island run.
Do you have any suggestions?

I mentioned in earlier comments above that the PAGMO_USE_TBB is set to disables, since it cannot find it when I set it to use. Is this reason for unsafe threading? I've again pushed all the files to my repository, the error occurs in line 96 of ManeuverApplication.cpp

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33684647/75027449-e6aec200-549e-11ea-9ed1-bdde0f82b4f8.gif)

**Comment by DominicDirkx** [comment]
Hi Jasper,

I think the problem is related to how you are creating an archipelago. Normally, your approach would be fine in Pagmo, but is not compatible with how Tudat calculates the fitness/propagates the dynamics. 

The issue lies in the fact that you create a problem once:

https://github.com/jasperwolfhagen/thesisProject/blob/master/BasicOptimisation.cpp#L89-L97

And then pass this to the archipelago object. This object then makes copies of the problem to use in each separate island. The manner in which these copies are made (in particular: shallow copies of all body object pointers) will results in the code not being threadsafe.

You can circumvent this, but using the fact that the archipelago comes with a push_back function:

https://esa.github.io/pagmo2/docs/cpp/archipelago.html#classpagmo_1_1archipelago_1abba64cd4e29bf8aa2e8ee2236935fb15

that allows you to add islands one by one. You can create an empty archipelago and then, in a for loop, create a new problem, algorithm and island, and then add this island to the archipelago.

Best,

Dominic

**Comment by jasperwolfhagen** [comment]
Dear Dominic,

Thank you for the solution, it has resolved the issue! I hope that for now, it will take some time before needing additional support, although I've one small question remaining.

I'm limiting the decision variables through box bounds to limit the search space and the objective space through inequality constraints. However, I would also like to limit the search space by only allowing multiples of the integer 3 for the epoch of thrusting, since through testing I found out that a higher precision does not yield a significant improvement in the result. 

Can I implement this additional 'constraint' onto the search space? I understand how I can impose it onto the objective space, but then the individual only gets rejected after fitness evaluation, while I want it not to be selected as decision variable in the first place. Unfortunately, I could not find any documentation about, but I cannot imagine that this is not an option.

Thanks again,
Jasper

**Comment by DominicDirkx** [comment]
Hi Jasper,

Good to hear that it works now! 

I'm not sure if the feature you're looking for is available in Pagmo. The place I'd look for it is in 'meta-problems' in their documentation. 

Best,

Dominic
