### ISSUE TITLE
Error in building the libraries after Tudat updated

### ISSUE THREAD

**Issue by weilunqin** [Tudat/tudat#612]
Dear Dominic,

I encountered a problem when building the libraries (before unit tests) after update the tudat. I asked this issue during the lecture break and the compile output file is here:
[Compile Output.txt](https://github.com/Tudat/tudat/files/4179855/Compile.Output.txt)

Cheers,
Weilun

**Comment by DominicDirkx** [comment]
Dear Weilun,

I suspect (but am not sure) that your issue is a result of a compiler version. Can you verify that:

- The code compiled and ran succesfully for all tests of Numerical Astrodynamics
- The modifications to the code are only those that were given in the Brightspace instructions
- You have not reinstalled Qt/compilers, or reset anything in the 'Kit' since Numerical Astrodynamics

Best,

Dominic

**Comment by DominicDirkx** [comment]
Dear Weilun,

Your issue may be the same as the one reported here:

https://github.com/Tudat/tudat/issues/611

Please follow the instructions to update the code, and let us know if ti works,

Best,

Dominic

**Comment by weilunqin** [comment]
Dear Dominic,


It works now. THX!!!


Cheers,
Weilun

**Comment by DominicDirkx** [comment]
Excellent! To all, don't forget to recompile _all_ unit tests, and rerun them in the near future
