### ISSUE TITLE
CMake CMP0048 warning

### ISSUE THREAD

**Issue by rodyo** [Tudat/tudat#640]
Most people's CMake version is now well above 3.0. In the current config, this gives the warning: 

```
CMake Warning (dev) at build/rapidjson-src/CMakeLists.txt:12 (PROJECT):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details. Use the cmake_policy
command to set the policy and suppress this warning.

The following variable(s) would be set to empty:

PROJECT_VERSION
PROJECT_VERSION_MAJOR
PROJECT_VERSION_MINOR
PROJECT_VERSION_PATCH

This warning is for project developers. Use -Wno-dev to suppress it.
```

This warning may scare people unaccustomed to it. It is easily, harmlessly and inconsequentially suppressed by simply adding a line: 

```
cmake_policy(SET CMP0048 NEW)
```

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version (but we will have a look at the open pull requests, a lot has changed in the code since, but I suspect some of your changes will still be very valuable!)
