### ISSUE TITLE
Definition of the initialTime inside the integratorSettings in shapeBasedTrajectoryDesign

### ISSUE THREAD

**Issue by ViktorJordanov** [Tudat/tudat#652]
Hi Marie,

In the part in which perturbations are added, the initialTime of the integratorSettings should be properly defined (with respect to J2000).

Also, in simsFlanaganModel.cpp, in the function convertTimeToLegSegment, rounding would help to make it more robust.

Kind regards,
Viktor

**Comment by MarieFayolle** [comment]
Hi Viktor, 

Thanks for the reminder!

@DominicDirkx this is just an issue to remind me to fix this properly in Tudat. Yesterday, we already discussed another fix with Viktor for his slightly modified version of Sims-Flanagan.

**Comment by MarieFayolle** [comment]
Changes required to fix this:

In **lowThrustLeg.h/cpp**, function **createLowThrustPropagatorSettings**:
1) Add additional input _double absoluteDepartureTime_
2) Modify the definition of the termination conditions to:
_terminationConditions.first = std::make_shared< propagators::PropagationTimeTerminationSettings >( absoluteDepartureTime, true );_
_terminationConditions.second = std::make_shared< propagators::PropagationTimeTerminationSettings >( absoluteDepartureTime + timeOfFlight_, true );_

Function **computeSemiAnalyticalAndFullPropagation**:
1) Add additional input _double absoluteDepartureTime_
2) Modify the definition of the integrator settings for the backward propagation to: 
_integratorSettings->initialTimeStep_ = - std::fabs( integratorSettings->initialTimeStep_ );
integratorSettings->initialTime_ = absoluteDepartureTime + timeOfFlight_ / 2.0;_

3) when storing the results, modify the epochs so that it starts at 0 and ends at TOF (that way it will be consistent with the analytical solution). so:
_epochsVector.push_back( itr->first - absoluteDepartureTime );
fullPropagationResults[ itr->first - absoluteDepartureTime ] = itr->second;
dependentVariablesHistory[ itr->first - absoluteDepartureTime ] = dependentVariableHistoryBackwardPropagation[ itr->first ];_

4) Modify the definition of the integrator settings for the forward propagation to:
_integratorSettings->initialTimeStep_ = std::fabs( integratorSettings->initialTimeStep_ );
integratorSettings->initialTime_ = absoluteDepartureTime  +  timeOfFlight_ / 2.0;_

5) Do the same trick as before to store the results of the forward propagation:
_epochsVector.push_back( itr->first - absoluteDepartureTime );
fullPropagationResults[ itr->first - absoluteDepartureTime ] = itr->second;
dependentVariablesHistory[ itr->first - absoluteDepartureTime ] = dependentVariableHistoryForwardPropagation[ itr->first ];_
 
6) At the end, after the following lines of code:
_// Reset initial integrator settings._
_integratorSettings->initialTimeStep_ = std::fabs( integratorSettings->initialTimeStep_ );_
Add: _integratorSettings->initialTime_ = departureTime;_

In **ShapeBasedMethod.h/cpp**, function **createLowThrustTranslationalStatePropagatorSettings**
1) Add additional input _double absoluteDepartureTime_
2) Modify the definition of the termination conditions to:
_terminationConditions.first = std::make_shared< propagators::PropagationTimeTerminationSettings >( absoluteDepartureTime, true );_
_terminationConditions.second = std::make_shared< propagators::PropagationTimeTerminationSettings >( absoluteDepartureTime + timeOfFlight_, true );_

In **SimsFlanagan.h/cpp**, function **createLowThrustTranslationalStatePropagatorSettings**: identical modifications
1) Add additional input _double absoluteDepartureTime_
2) Modify the definition of the termination conditions:
_terminationConditions.first = std::make_shared< propagators::PropagationTimeTerminationSettings >( absoluteDepartureTime, true );
terminationConditions.second = std::make_shared< propagators::PropagationTimeTerminationSettings >( absoluteDepartureTime + timeOfFlight_, true );_

**Comment by DominicDirkx** [comment]
NOTE: This Tudat version is no longer supported. See https://docs.tudat.space/en/stable/ and https://github.com/tudat-team/tudat-bundle for the new version
